# libgda ja.po
# Copyright (C) 1999 Free Software Foundation, Inc.
# Akira TAGOH <tagoh@gnome.gr.jp>, 2000.
#
msgid ""
msgstr ""
"Project-Id-Version: libgda CVS-20001008\n"
"POT-Creation-Date: 2000-10-10 00:35+0900\n"
"PO-Revision-Date: 2000-10-10 00:43+0900\n"
"Last-Translator: Akira TAGOH <tagoh@gnome.gr.jp>\n"
"Language-Team: Japanese <translation@gnome.gr.jp>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=euc-jp\n"
"Content-Transfer-Encoding: 8bit\n"

#: lib/gda-client/gda-connection-pool.c:169
#, c-format
msgid "could not open connection to %s"
msgstr "%s へ接続することが出来ませんでした"

#: lib/gda-client/gda-connection-pool.c:180
#, c-format
msgid "Data source %s not found"
msgstr "データソース %s は見つかりませんでした"

#: lib/gda-client/gda-connection.c:166 lib/gda-client/gda-error.c:116
#, c-format
msgid "%s: The server didn't respond."
msgstr "%s: サーバは応答しませんでした"

#: lib/gda-client/gda-connection.c:170 lib/gda-client/gda-error.c:120
#, c-format
msgid "%s: An Error occured in the CORBA system."
msgstr "%s: CORBA システムでエラーが発生しました"

#: lib/gda-client/gda-connection.c:453
#, c-format
msgid "Database '%s' not found in system configuration"
msgstr "データベース '%s' はシステム設定から見つかりませんでした"

#: lib/gda-client/gda-connection.c:469
msgid "Could not open CORBA factory"
msgstr "CORBA ファクトリを開くことが出来ませんでした"

#: lib/gda-client/gda-field.c:187
msgid "<NULL>"
msgstr "<NULL>"

#: lib/gda-client/gda-field.c:193 lib/gda-client/gda-field.c:195
msgid "<Unknown GDA Type(NULL)>"
msgstr "<未知の GDA タイプ(NULL)>"

#: lib/gda-client/gda-field.c:208
msgid "TRUE"
msgstr "TRUE"

#: lib/gda-client/gda-field.c:209
msgid "FALSE"
msgstr "FALSE"

#: lib/gda-common/gda-corba.c:72
msgid "True"
msgstr "True"

#: lib/gda-common/gda-corba.c:72
msgid "False"
msgstr "False"

#: lib/gda-common/gda-corba.c:119
#, c-format
msgid "CORBA System exception: %s"
msgstr "CORBA システム例外: %s"

#: lib/gda-common/gda-init.c:32
msgid "Attempt to initialize an already initialized client"
msgstr "初期化を試みましたがすでにクライアントは初期化されています"

#: lib/gda-common/gda-log.c:29
msgid "Saving log...x"
msgstr "ログを保存中...x"

#. compose message
#: lib/gda-common/gda-log.c:50
msgid "ERROR: "
msgstr "エラー: "

#: lib/gda-common/gda-log.c:50
msgid "MESSAGE: "
msgstr "メッセージ: "

#: lib/gda-common/gda-thread.c:150
msgid "thread is already running"
msgstr "スレッドはすでに実行中です"

#: lib/gda-common/gda-xml-database.c:224
#, c-format
msgid "table %s already exists"
msgstr "テーブル %s はすでに存在しています"

#: lib/gda-common/gda-xml-database.c:388
#, c-format
msgid "%p is not a valid table"
msgstr "%p は有効なテーブルではありません"

#: lib/gda-server/gda-server-error.c:169
msgid "Could not get pointer to server implementation"
msgstr "サーバの実装へのポインタを取得することが出来ませんでした"

#: lib/gda-server/gda-server-impl-connection.c:106
#: lib/gda-server/gda-server-impl-connection.c:115
#: lib/gda-server/gda-server-impl-connection.c:122
#: lib/gda-server/gda-server-impl-connection.c:131
#: lib/gda-server/gda-server-impl-connection.c:138
#: lib/gda-server/gda-server-impl-connection.c:147
#: lib/gda-server/gda-server-impl-connection.c:154
#: lib/gda-server/gda-server-impl-connection.c:163
#: lib/gda-server/gda-server-impl-recordset.c:113
#: lib/gda-server/gda-server-impl-recordset.c:122
#: lib/gda-server/gda-server-impl-recordset.c:129
#: lib/gda-server/gda-server-impl-recordset.c:144
#: lib/gda-server/gda-server-impl-recordset.c:153
#: lib/gda-server/gda-server-impl-recordset.c:160
#: lib/gda-server/gda-server-impl-recordset.c:169
#: lib/gda-server/gda-server-impl-recordset.c:176
#: lib/gda-server/gda-server-impl-recordset.c:185
#: lib/gda-server/gda-server-impl-recordset.c:192
#: lib/gda-server/gda-server-impl-recordset.c:200
#: lib/gda-server/gda-server-impl-recordset.c:209
#: lib/gda-server/gda-server-impl-recordset.c:216
#: lib/gda-server/gda-server-impl-recordset.c:224
#: lib/gda-server/gda-server-impl-recordset.c:232
#: lib/gda-server/gda-server-impl-recordset.c:274
#: lib/gda-server/gda-server-impl-recordset.c:284
#: lib/gda-server/gda-server-impl-recordset.c:292
#: lib/gda-server/gda-server-impl-recordset.c:300
#: lib/gda-server/gda-server-impl-recordset.c:308
#: lib/gda-server/gda-server-impl-recordset.c:316
#: lib/gda-server/gda-server-impl-recordset.c:325
#: lib/gda-server/gda-server-impl-recordset.c:333
#: lib/gda-server/gda-server-impl-recordset.c:341
#, c-format
msgid "%s not implemented"
msgstr "%s は実装されていません"

#: lib/gda-server/gda-server-impl-connection.c:255
#, c-format
msgid "impl_GDA_Connection_open: opening connection with DSN: %s"
msgstr "impl_GDA_Connection_open: DSN '%s' で接続を開いています"

#: lib/gda-server/gda-server-impl-recordset.c:240
#: lib/gda-server/gda-server-impl-recordset.c:248
#, c-format
msgid "%s: not implemented"
msgstr "%s: 実装されていません"

#: lib/gda-server/gda-server-impl-recordset.c:434
#, c-format
msgid "%s: an error ocurred while fetching data"
msgstr "%s: データ取得中にエラーが発生しました"

#: lib/gda-server/gda-server-impl-recordset.c:473
#, c-format
msgid "%s: length = %d"
msgstr "%s: 長さ = %d"

#: lib/gda-server/gda-server-impl-recordset.c:486
#, c-format
msgid "%s: sending field description for '%s'"
msgstr "%s: '%s' のためのフィールドの記述を送信中"

#: lib/gda-server/gda-server-impl.c:114
#, c-format
msgid "Starting provider %s with no implementation functions"
msgstr "未実装の機能をプロバイダ %s で開始しています"

#: lib/gda-server/gda-server-impl.c:141
#: report/server/gda-report-server-main.c:120
msgid ""
"OAF doesn't know about our IID; indicates broken installation. Exiting..."
msgstr ""
"OAF は IID について知りません; インストールが失敗しているかもれません. "
"終了します..."

#: lib/gda-server/gda-server-impl.c:144
msgid ""
"Another instance of this provider is already registered with OAF. Exiting..."
msgstr ""
"このプロバイダの別のインスタンスはすでに OAF が登録しています. 終了します..."

#: lib/gda-server/gda-server-impl.c:147
msgid "Unknown error registering this provider with OAF. Exiting"
msgstr "OAF がこのプロバイダを登録中に未知のエラーが発生しました. 終了します"

#: lib/gda-server/gda-server-impl.c:151
#, c-format
msgid "Registered with ID = %s"
msgstr "ID = %s で登録しました"

#: lib/gda-server/gda-server-impl.c:241
#, c-format
msgid "CORBA system exception %s"
msgstr "CORBA システム例外 %s"

#: lib/gda-server/gda-server-impl.c:244
#, c-format
msgid "CORBA user exception: %s"
msgstr "CORBA ユーザ例外: %s"

#: lib/gda-server/gda-server-init.c:39 lib/gda-server/gda-server-init.c:45
#, c-format
msgid "Received signal %d, shutting down"
msgstr "シグナル %d を受信しました, 終了します"

#: lib/gda-server/gda-server-init.c:49
#, c-format
msgid "Received signal %d. Ignoring"
msgstr "シグナル %d を受信しました, 無視します"

#: lib/gda-server/gda-server-init.c:97
msgid "Attempt to initialize an already initialized provider"
msgstr "初期化を試みましたがすでにプロバイダは初期化されています"

#: providers/gda-interbase-server/gda-interbase-connection.c:252
#: providers/gda-ldap-server/gda-ldap-connection.c:263
#: providers/gda-mdb-server/gda-mdb-connection.c:351
#: providers/gda-mysql-server/gda-mysql-connection.c:378
#: providers/gda-odbc-server/gda-odbc-connection.c:600
#: providers/gda-odbc-server/gda-odbc-connection.c:633
#: providers/gda-oracle-server/gda-oracle-connection.c:417
#: providers/gda-postgres-server/gda-postgres-connection.c:771
#: providers/gda-sybase-server/gda-sybase-error.c:106
#, c-format
msgid "error '%s' at %s"
msgstr "エラー '%s' が %s で発生しました"

#: providers/gda-interbase-server/gda-interbase-connection.c:257
#: providers/gda-interbase-server/gda-interbase-connection.c:258
#: providers/gda-ldap-server/gda-ldap-connection.c:268
#: providers/gda-ldap-server/gda-ldap-connection.c:269
#: providers/gda-mdb-server/gda-mdb-connection.c:355
#: providers/gda-mdb-server/gda-mdb-connection.c:356
#: providers/gda-mysql-server/gda-mysql-connection.c:382
#: providers/gda-mysql-server/gda-mysql-connection.c:383
#: providers/gda-odbc-server/gda-odbc-connection.c:602
#: providers/gda-odbc-server/gda-odbc-connection.c:603
#: providers/gda-odbc-server/gda-odbc-connection.c:635
#: providers/gda-odbc-server/gda-odbc-connection.c:636
#: providers/gda-oracle-server/gda-oracle-connection.c:422
#: providers/gda-oracle-server/gda-oracle-connection.c:423
#: providers/gda-postgres-server/gda-postgres-connection.c:778
#: providers/gda-postgres-server/gda-postgres-connection.c:779
#: providers/gda-sybase-server/gda-sybase-error.c:115
#: providers/gda-sybase-server/gda-sybase-error.c:116
msgid "Not available"
msgstr "利用できません"

#: providers/gda-interbase-server/gda-interbase-connection.c:259
#: providers/gda-ldap-server/gda-ldap-connection.c:270
#: providers/gda-mdb-server/gda-mdb-connection.c:357
#: providers/gda-mysql-server/gda-mysql-connection.c:384
#: providers/gda-oracle-server/gda-oracle-connection.c:424
#: providers/gda-postgres-server/gda-postgres-connection.c:780
#: providers/gda-sybase-server/gda-sybase-error.c:117
msgid "error"
msgstr "エラー"

#: providers/gda-ldap-server/main-ldap.c:68
msgid "Could not register LDAP provider implementation"
msgstr "LDAP プロバイダの実装を登録することが出来ませんでした"

#: providers/gda-interbase-server/gda-interbase-connection.c:251
#, c-format
msgid "Error code %ld"
msgstr "エラーコード %ld"

#: providers/gda-interbase-server/main-interbase.c:69
msgid "Could not register INTERBASE provider implementation"
msgstr "INTERBASE プロバイダの実装を登録することが出来ませんでした"

#: providers/gda-mail-server/gda-mail-connection.c:108
#: providers/gda-mdb-server/gda-mdb-connection.c:224
#: providers/gda-mysql-server/gda-mysql-connection.c:251
#: providers/gda-oracle-server/gda-oracle-connection.c:295
#: providers/gda-postgres-server/gda-postgres-connection.c:511
#: providers/gda-sybase-server/gda-sybase-connection.c:253
#, c-format
msgid "Unhandled SCHEMA_QTYPE %d"
msgstr "SCHEMA_QTYPE %d は扱えません"

#: providers/gda-mail-server/main-mail.c:69
msgid "Could not register Mail provider implementation"
msgstr "メールプロバイダの実装を登録することが出来ませんでした"

#. execute command
#: providers/gda-mdb-server/gda-mdb-command.c:86
#: providers/gda-mysql-server/gda-mysql-command.c:87
#: providers/gda-sybase-server/gda-sybase-command.c:116
#, c-format
msgid "executing command '%s'"
msgstr "コマンド '%s' を実行しています"

#: providers/gda-mdb-server/gda-mdb-command.c:88
#: providers/gda-mysql-server/gda-mysql-command.c:89
#, c-format
msgid "info '%s'"
msgstr "情報 '%s'"

#: providers/gda-mdb-server/gda-mdb-connection.c:137
#: providers/gda-mysql-server/gda-mysql-connection.c:148
#, c-format
msgid ""
"%s:%d: You cannot provide a UNIX_SOCKET if you also provide either a HOST or "
"a PORT. Please remove the UNIX_SOCKET, or remove both the HOST and PORT "
"options"
msgstr ""
"%s:%d: UNIX_SOCKET を提供することが出来ません. HOST または PORT "
"のどちらかを提供するなら, UNIX_SOCKET を削除するか, HOST と PORT "
"の両方のオプションを削除してください"

#: providers/gda-mdb-server/gda-mdb-connection.c:147
#, c-format
msgid "%s:%d: You must  provide the filename with the MS Access database"
msgstr "%s:%d: MS Access データベースのファイル名を提供しなければなりません"

#: providers/gda-mdb-server/gda-mdb-connection.c:152
#, c-format
msgid "Opening connection with filename=%s, user=%s, password=%s"
msgstr "ファイル名=%s, ユーザ=%s, パスワード=%s で接続を開いています"

#: providers/gda-mdb-server/gda-mdb-connection.c:406
#: providers/gda-mysql-server/gda-mysql-connection.c:433
msgid "mysql_recset is NULL"
msgstr "mysql_recset は NULL です"

#: providers/gda-mdb-server/gda-mdb-connection.c:448
#: providers/gda-mysql-server/gda-mysql-connection.c:475
#: providers/gda-sybase-server/gda-sybase-connection.c:407
msgid "No table name given for SCHEMA_COLS"
msgstr "SCHEMA_COLS のためのテーブル名が与えられていません"

#: providers/gda-mdb-server/main-mdb.c:69
#: providers/gda-mysql-server/main-mysql.c:69
msgid "Could not register MySQL provider implementation"
msgstr "MySQL プロバイダの実装を登録することが出来ませんでした"

#: providers/gda-mysql-server/gda-mysql-connection.c:162
#, c-format
msgid ""
"Opening connection with user=%s, password=%s, host=%s, port=%s, "
"unix_socket=%s"
msgstr ""
"ユーザ=%s, パスワード=%s, ホスト=%s, ポート=%s, unix ソケット=%s "
"で接続を開いています"

#: providers/gda-odbc-server/gda-odbc-connection.c:280
#, c-format
msgid "gda_odbc_connection_open_schema: Unhandled SCHEMA_QTYPE %d\n"
msgstr "gda_odbc_connection_open_schema: SCHEMA_QTYPE %d は扱えません\n"

#: providers/gda-odbc-server/gda-odbc-connection.c:617
#: providers/gda-odbc-server/gda-odbc-connection.c:618
#: providers/gda-odbc-server/gda-odbc-connection.c:619
#: providers/gda-odbc-server/gda-odbc-connection.c:650
#: providers/gda-odbc-server/gda-odbc-connection.c:651
#: providers/gda-odbc-server/gda-odbc-connection.c:652
msgid "no text"
msgstr "テキストがありません"

#: providers/gda-odbc-server/main-odbc.c:68
msgid "Could not register ODBC provider implementation"
msgstr "ODBC プロバイダの実装を登録することが出来ませんでした"

#: providers/gda-oracle-server/gda-oracle-command.c:195
msgid "Could not allocate statement handle"
msgstr "ステートメントハンドルを割り当てることが出来ませんでした"

#: providers/gda-oracle-server/gda-oracle-command.c:199
msgid "command object being created without associated connection"
msgstr "コマンドオブジェクトは接続なしで作成しました"

#: providers/gda-oracle-server/gda-oracle-command.c:226
#, c-format
msgid "Executing command '%s'"
msgstr "コマンド '%s' を実行しています"

#: providers/gda-oracle-server/gda-oracle-connection.c:113
msgid "error in OCIHandleAlloc() HTYPE_SVCCTX"
msgstr "OCIHandleAlloc() HTYPE_SVCCTX でエラーが発生しました"

#: providers/gda-oracle-server/gda-oracle-connection.c:116
msgid "error in OCIHandleAlloc() HTYPE_SERVER"
msgstr "OCIHandleAlloc() HTYPE_SERVER でエラーが発生しました"

#: providers/gda-oracle-server/gda-oracle-connection.c:119
msgid "error in OCIHandleAlloc() HTYPE_ERROR"
msgstr "OCIHandleAlloc() HTYPE_ERROR でエラーが発生しました"

#: providers/gda-oracle-server/gda-oracle-connection.c:370
#, c-format
msgid "Unknown ORACLE type %ld"
msgstr "未知の ORACLE タイプ %ld です"

#: providers/gda-oracle-server/gda-oracle-recordset.c:115
msgid "Unknown ORACLE data type in fill_field_values"
msgstr "fill_field_values に未知の ORACLE データタイプがあります"

#: providers/gda-oracle-server/gda-oracle-recordset.c:150
msgid "recordset object being created without associated connection"
msgstr "レコードセットオブジェクトは接続なしで作成しました"

#: providers/gda-oracle-server/main-oracle.c:68
msgid "Could not register ORACLE provider implementation"
msgstr "ORACLE プロバイダの実装を登録することが出来ませんでした"

#: providers/gda-postgres-server/gda-postgres-connection.c:880
#: providers/gda-postgres-server/gda-postgres-connection.c:992
msgid "postgres_recset is NULL"
msgstr "postgres_recset は NULL です"

#: providers/gda-postgres-server/main-postgres.c:68
msgid "Could not register PostgreSQL provider implementation"
msgstr "PostgreSQL プロバイダの実装を登録することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-command.c:111
msgid "Connection seems to be dead"
msgstr "接続は切れたようです"

#: providers/gda-sybase-server/gda-sybase-command.c:131
msgid "Filling command structure failed\n"
msgstr "コマンド構造体の充填に失敗しました\n"

#: providers/gda-sybase-server/gda-sybase-command.c:143
msgid "sending cmd failed"
msgstr "コマンドの送信に失敗しました"

#: providers/gda-sybase-server/gda-sybase-command.c:150
msgid "Allocating recordset failed"
msgstr "レコードセットの割り当てに失敗しました"

#: providers/gda-sybase-server/gda-sybase-command.c:160
msgid "Getting recordset userdata failed"
msgstr "レコードセットのユーザデータの取得に失敗しました"

#: providers/gda-sybase-server/gda-sybase-command.c:218
msgid "Command execution finished, all results processed"
msgstr "コマンドの実行は完了しました, すべての結果を処理しました"

#: providers/gda-sybase-server/gda-sybase-command.c:222
msgid "Command failed"
msgstr "コマンドは失敗しました"

#: providers/gda-sybase-server/gda-sybase-command.c:226
msgid "Execution of resultless command succeeded"
msgstr "結果のない実行コマンドは成功しました"

#: providers/gda-sybase-server/gda-sybase-command.c:242
#, c-format
msgid "ct_results() returned %x"
msgstr "ct_results() は %x を返しました"

#: providers/gda-sybase-server/gda-sybase-command.c:252
msgid "No further results, command completly succeeded."
msgstr "深刻な結果はありません, コマンドは完全に成功しました"

#: providers/gda-sybase-server/gda-sybase-command.c:256
msgid "An error occured during command execution."
msgstr "コマンド実行中にエラーが発生しました"

#: providers/gda-sybase-server/gda-sybase-command.c:263
msgid "Cmd execution returned unknown result, may be an error"
msgstr "コマンド実行は未知の結果を返しました, エラーかもしれません"

#: providers/gda-sybase-server/gda-sybase-command.c:276
msgid "No data returned, freeing recordset structure"
msgstr "データが返されません, レコードセット構造体を開放しています"

#: providers/gda-sybase-server/gda-sybase-command.c:307
#: providers/gda-sybase-server/gda-sybase-command.c:319
msgid "Freeing command structure failed"
msgstr "コマンド構造体の開放に失敗しました"

#: providers/gda-sybase-server/gda-sybase-connection.c:133
msgid "Error allocating error structure"
msgstr "エラー構造体の割り当て中にエラーが発生しました"

#: providers/gda-sybase-server/gda-sybase-connection.c:141
msgid "Not enough memory for sybase_Connection"
msgstr "sybase_Connection のための十分なメモリがありません"

#: providers/gda-sybase-server/gda-sybase-connection.c:397
#, c-format
msgid "schema_cols: table_name '%s'"
msgstr "schema_cols: table_name '%s'"

#: providers/gda-sybase-server/gda-sybase-connection.c:413
msgid "Could not allocate command structure"
msgstr "コマンド構造体を割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:435
msgid "Could not allocate enough memory for query"
msgstr "クエリのための十分なメモリを割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:449
msgid "Could not get recordset in schema_cols"
msgstr "schema_cols からレコードセットを取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:481
#: providers/gda-sybase-server/gda-sybase-connection.c:558
#, c-format
msgid "schema_tables: table name = '%s'"
msgstr "schema_tables: テーブル名 = '%s'"

#: providers/gda-sybase-server/gda-sybase-connection.c:489
#: providers/gda-sybase-server/gda-sybase-connection.c:566
#, c-format
msgid "schema_tables: table_schema = '%s'"
msgstr "schema_tables: table_schema = '%s'"

#: providers/gda-sybase-server/gda-sybase-connection.c:494
#, c-format
msgid "schema_procedures: proc_catalog = '%s' UNUSED!\n"
msgstr "schema_procedures: proc_catalog = %s' は使っていません!\n"

#: providers/gda-sybase-server/gda-sybase-connection.c:498
#, c-format
msgid "schema_procs: invalid constraint type %d"
msgstr "schema_procs: 制約タイプ %d は無効です"

#: providers/gda-sybase-server/gda-sybase-connection.c:508
msgid "Could not allocate cmd structure"
msgstr "コマンド構造体を割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:571
#, c-format
msgid "schema_procedures: proc_catalog = '%s' UNUSED!"
msgstr "schema_procedures: proc_catalog = '%s' は使っていません!"

#: providers/gda-sybase-server/gda-sybase-connection.c:575
#, c-format
msgid "schema_tables: invalid constraint type %d"
msgstr "schema_tables: 制約タイプ %d は無効です"

#: providers/gda-sybase-server/gda-sybase-connection.c:636
#, c-format
msgid "Invalid or unsupported constraint type: %d"
msgstr "制約タイプは無効またはサポートしていません: %d"

#: providers/gda-sybase-server/gda-sybase-connection.c:677
msgid "Could not allocate Gda_ServerCommand"
msgstr "Gda_ServerCommand の割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:707
#: providers/gda-sybase-server/gda-sybase-connection.c:712
#, c-format
msgid "connection status: %x"
msgstr "接続状況: %x"

#: providers/gda-sybase-server/gda-sybase-connection.c:708
#, c-format
msgid "return code: %x"
msgstr "戻り値: %x"

#: providers/gda-sybase-server/gda-sybase-connection.c:745
msgid "attempting reconnection"
msgstr "再接続を試みています"

#: providers/gda-sybase-server/gda-sybase-connection.c:884
#, c-format
msgid "Reconnected to '%s'"
msgstr "'%s' へ再接続しました"

#: providers/gda-sybase-server/gda-sybase-connection.c:886
#, c-format
msgid "Connected to %s"
msgstr "%s に接続完了"

#: providers/gda-sybase-server/gda-sybase-connection.c:894
#, c-format
msgid "Selected database '%s'"
msgstr "データベース '%s' を選択しました"

#: providers/gda-sybase-server/gda-sybase-connection.c:923
#, c-format
msgid "%s: Could not allocate cmd structure"
msgstr "%s: コマンド構造体を割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:932
#, c-format
msgid "%s: Could not allocate memory for cmd string"
msgstr "%s: コマンド文字列のためのメモリを割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:945
#, c-format
msgid "%s: ct_command failed"
msgstr "%s: ct_command は失敗しました"

#: providers/gda-sybase-server/gda-sybase-connection.c:954
#, c-format
msgid "%s: sending command failed"
msgstr "%s: コマンドの送信は失敗しました"

#: providers/gda-sybase-server/gda-sybase-connection.c:965
#, c-format
msgid "%s: selecting database failed"
msgstr "%s: データベースの選択に失敗しました"

#: providers/gda-sybase-server/gda-sybase-connection.c:983
#, c-format
msgid "%s: use command failed"
msgstr "%s: ユーザコマンドは失敗しました"

#: providers/gda-sybase-server/gda-sybase-connection.c:1010
msgid "Could not allocate locale structure"
msgstr "ロケール構造体を割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:1016
#, c-format
msgid "Could not set locale to '%s'"
msgstr "'%s' にロケールを設定することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:1022
#, c-format
msgid "Could not configure locale to be '%s'"
msgstr "'%s' にロケールを設定することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:1027
msgid "Could not drop locale structure"
msgstr "ロケール構造体をドロップすることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:1040
#, c-format
msgid "Fatal error: %s\n"
msgstr "致命的なエラー: %s\n"

#: providers/gda-sybase-server/gda-sybase-error.c:62
#, c-format
msgid "gda_sybase_error_make(%p,%p,%p,%p)"
msgstr "gda_sybase_error_make(%p,%p,%p,%p)"

#: providers/gda-sybase-server/gda-sybase-error.c:71
#, c-format
msgid "No error flag ist set, though %s is called. This may be a bug."
msgstr ""
"%s が呼ばれたにもかかわらずエラーフラグが設定されていません. "
"これは不具合かもしれません"

#: providers/gda-sybase-server/gda-sybase-error.c:135
msgid "cs_diag() initialized"
msgstr "cs_diag() を初期化しました"

#: providers/gda-sybase-server/gda-sybase-error.c:138
msgid "Could not initialize cs_diag()"
msgstr "cs_diag() を初期化することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:145
msgid "ct_diag() initialized"
msgstr "ct_diag() を初期化しました"

#: providers/gda-sybase-server/gda-sybase-error.c:148
msgid "Could not initialize ct_diag()"
msgstr "ct_diag() を初期化することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:182
#, c-format
msgid "%s could not find server implementation"
msgstr "%s をサーバの実装から見付けることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:188
#, c-format
msgid "%s could not get cnc userdata"
msgstr "%s は cnc ユーザデータを取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:200
msgid "Could not get # of messages"
msgstr "メッセージ数を取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:205
#, c-format
msgid "%d ctlib messages to fetch"
msgstr "%d 個の ctlib メッセージを取得しました"

#: providers/gda-sybase-server/gda-sybase-error.c:207
#, c-format
msgid "%d ctlib message to fetch"
msgstr "%d 個の ctlib メッセージを取得しました"

#: providers/gda-sybase-server/gda-sybase-error.c:243
msgid "error is nullpointer in gda_sybase_messages_handle"
msgstr "gda_sybase_messages_handle の NULL ポインタはエラーです"

#: providers/gda-sybase-server/gda-sybase-error.c:268
#: providers/gda-sybase-server/gda-sybase-error.c:335
#: providers/gda-sybase-server/gda-sybase-error.c:378
msgid "Could not get # of server messages"
msgstr "サーバメッセージ数を取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:276
#, c-format
msgid "Fetching %d client messages"
msgstr "%d 個のクライアントメッセージを取得しています"

#: providers/gda-sybase-server/gda-sybase-error.c:278
#, c-format
msgid "Fetching %d client message"
msgstr "%d 個のクライアントメッセージを取得しています"

#: providers/gda-sybase-server/gda-sybase-error.c:287
#, c-format
msgid "Could not get client msg # %d"
msgstr "クライアントメッセージ番号 %d を取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:303
msgid "Could not get # of client messages"
msgstr "クライアントメッセージ数を取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:311
msgid "Could not clear client messages"
msgstr "クライアントメッセージを消去することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:343
#, c-format
msgid "Fetching %d server messages"
msgstr "%d 個のサーバメッセージを取得しています"

#: providers/gda-sybase-server/gda-sybase-error.c:345
#, c-format
msgid "Fetching %d server message"
msgstr "%d 個のサーバメッセージを取得しています"

#: providers/gda-sybase-server/gda-sybase-error.c:354
#, c-format
msgid "Could not get server msg # %d"
msgstr "サーバメッセージ番号 %d を取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:386
msgid "Could not clear server messages"
msgstr "サーバメッセージを消去することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:408
#: providers/gda-sybase-server/gda-sybase-error.c:444
msgid "Could not get # of cslib messages"
msgstr "cslib メッセージ数を取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:416
#, c-format
msgid "Fetching %d cslib messages"
msgstr "%d 個の cslib メッセージを取得してします"

#: providers/gda-sybase-server/gda-sybase-error.c:418
#, c-format
msgid "Fetchong %d cslib message"
msgstr "%d 個の cslib メッセージを取得しています"

#: providers/gda-sybase-server/gda-sybase-error.c:428
#, c-format
msgid "Could not get cslib msg # %d"
msgstr "cslib メッセージ番号 %d を取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:452
msgid "Could not clear cslib messages"
msgstr "cslib メッセージを消去することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:584
msgid "Server message:"
msgstr "サーバメッセージ:"

#: providers/gda-sybase-server/gda-sybase-error.c:593
msgid "Client message:"
msgstr "クライアントメッセージ:"

#: providers/gda-sybase-server/gda-sybase-error.c:600
msgid "CS-Library error:"
msgstr "CS-Library エラー:"

#: providers/gda-sybase-server/gda-sybase-recordset.c:152
#, c-format
msgid "fetch error at row %d"
msgstr "%d 列目の取得でエラーが発生しました"

#: providers/gda-sybase-server/gda-sybase-recordset.c:159
#, c-format
msgid "CS_END_DATA on row %d; canceling"
msgstr "%d 列目で CS_END_DATA; キャンセル中"

#: providers/gda-sybase-server/gda-sybase-recordset.c:168
#, c-format
msgid "%s: Error (%d)"
msgstr "%s: エラー (%d)"

#: providers/gda-sybase-server/gda-sybase-recordset.c:343
msgid "Failed fetching # of columns"
msgstr "カラム数の取得に失敗しました"

#: providers/gda-sybase-server/gda-sybase-recordset.c:349
#, c-format
msgid "Counted %d columns"
msgstr "%d カラムをカウントしました"

#: providers/gda-sybase-server/gda-sybase-recordset.c:356
#, c-format
msgid "%s could not allocate datafmt info"
msgstr "%s はデータフォーマット情報を割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-recordset.c:366
#, c-format
msgid "%s could not allocate data fields"
msgstr "%s はデータフィールドを割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-recordset.c:384
#, c-format
msgid "ct_describe on col # %d"
msgstr "カラム番号 %d で ct_describe します"

#: providers/gda-sybase-server/gda-sybase-recordset.c:391
#, c-format
msgid "ct_describe on col # %d failed"
msgstr "カラム番号 %d で ct_describe に失敗しました"

#: providers/gda-sybase-server/gda-sybase-recordset.c:397
#, c-format
msgid "ct_describe(%d): '%s', %d (%s)"
msgstr "ct_describe(%d): '%s', %d (%s)"

#: providers/gda-sybase-server/gda-sybase-recordset.c:406
msgid "could not allocate data holder"
msgstr "データホルダーを割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-recordset.c:416
msgid "could not ct_bind data holder to column"
msgstr "カラムにデータホルダーを ct_bind することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-recordset.c:423
msgid "illegal type detected, aborting"
msgstr "不当なタイプを検出しました, 中止しています"

#: providers/gda-sybase-server/gda-sybase-recordset.c:429
msgid "could not allocate field"
msgstr "フィールドを割り当てることが出来ませんでした"

#: providers/gda-sybase-server/main-sybase.c:73
msgid "Could not register gda-sybase provider implementation"
msgstr "gda-sybase プロバイダの実装を登録することが出来ませんでした"

#: report/gda-report-engine.c:71
#, c-format
msgid "CORBA exception unloading report engine: %s"
msgstr "CORBA 例外はレポートエンジンを取り外しています: %s"

#: report/server/gda-report-server-main.c:43
#: report/server/gda-report-server-main.c:50
#, c-format
msgid "Received signal %d, shutting down."
msgstr "シグナル %d を受信しました, 終了します"

#: report/server/gda-report-server-main.c:54
#, c-format
msgid "Received signal %d, shutting down cleanly"
msgstr "シグナル %d を受信しました, きれいに終了します"

#: report/server/gda-report-server-main.c:96
msgid "Failed to initialize OAF: please mail bug report to OAF maintainers"
msgstr "OAF の初期化に失敗: OAF メンテナへ不具合報告をメールしてください"

#: report/server/gda-report-server-main.c:106
msgid "Could not activate report engine"
msgstr "レポートエンジンを始動させることが出来ませんでした"

#: report/server/gda-report-server-main.c:123
msgid ""
"Another instance of the report engine is already registered with OAF. "
"Exiting..."
msgstr ""
"レポートエンジンの別のインスタンスはすでに OAF が登録しています. "
"終了します..."

#: report/server/gda-report-server-main.c:126
msgid "Unknown error registering report engine with OAF. Exiting"
msgstr "OAF がレポートエンジンを登録中に未知のエラーが発生しました. 終了します"

#: report/server/gda-report-server-main.c:130
#, c-format
msgid "Registered report engine with ID = %s"
msgstr "ID = %s でレポートエンジンを登録しました"

#: tools/gda-run.c:29
msgid "database name"
msgstr "データベース名"

#: tools/gda-run.c:29
msgid "DATABASE"
msgstr "DATABASE"

#: tools/gda-run.c:30
msgid "user name"
msgstr "ユーザ名"

#: tools/gda-run.c:30
msgid "USER-NAME"
msgstr "USER-NAME"

#: tools/gda-run.c:31
msgid "password"
msgstr "パスワード"

#: tools/gda-run.c:31
msgid "PASSWORD"
msgstr "PASSWORD"

#: tools/gda-run.c:32
msgid "file name"
msgstr "ファイル名"

#: tools/gda-run.c:32
msgid "FILE-NAME"
msgstr "FILE-NAME"

#: tools/gda-run.c:104
#, c-format
msgid "%s: misconfigured DSN entry"
msgstr "%s: DSN エントリの設定ミスです"

#: tools/gda-run.c:119
#, c-format
msgid "%s: data source '%s' not found\n"
msgstr "%s: データソース '%s' は見つかりませんでした\n"
