# libgda ja.po
# Copyright (C) 1999 Free Software Foundation, Inc.
# Akira TAGOH <tagoh@gnome.gr.jp>, 2000-2001.
#
msgid ""
msgstr ""
"Project-Id-Version: libgda CVS-20010407\n"
"POT-Creation-Date: 2001-09-16 22:13+0200\n"
"PO-Revision-Date: 2001-04-07 12:45+0900\n"
"Last-Translator: Akira TAGOH <tagoh@gnome.gr.jp>\n"
"Language-Team: Japanese <translation@gnome.gr.jp>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=euc-jp\n"
"Content-Transfer-Encoding: 8bit\n"

#: lib/gda-client/gda-connection-pool.c:268
#, c-format
msgid "could not open connection to %s"
msgstr "%s へ接続することが出来ませんでした"

#: lib/gda-client/gda-connection-pool.c:281
#, c-format
msgid "Data source %s not found"
msgstr "データソース %s は見つかりませんでした"

#: lib/gda-client/gda-connection.c:447
#, c-format
msgid "Database '%s' not found in system configuration"
msgstr "データベース '%s' はシステム設定から見つかりませんでした"

#: lib/gda-client/gda-connection.c:451 lib/gda-client/gda-connection.c:468
msgid "[GDA Client Library]"
msgstr ""

#: lib/gda-client/gda-connection.c:467
msgid "Could not open CORBA factory"
msgstr "CORBA ファクトリを開くことが出来ませんでした"

#: lib/gda-client/gda-field.c:228
msgid "<NULL>"
msgstr "<NULL>"

#: lib/gda-client/gda-field.c:233 lib/gda-client/gda-field.c:236
msgid "<Unknown GDA Type(NULL)>"
msgstr "<未知の GDA タイプ(NULL)>"

#: lib/gda-client/gda-field.c:249
msgid "TRUE"
msgstr "TRUE"

#: lib/gda-client/gda-field.c:251
msgid "FALSE"
msgstr "FALSE"

#: lib/gda-common/gda-corba.c:88
#, c-format
msgid "CORBA System exception: %s"
msgstr "CORBA システム例外: %s"

#: lib/gda-common/gda-corba.c:123
msgid "True"
msgstr "True"

#: lib/gda-common/gda-corba.c:124
msgid "False"
msgstr "False"

#: lib/gda-common/gda-error.c:128
#, c-format
msgid "%s: The server didn't respond."
msgstr "%s: サーバは応答しませんでした"

#: lib/gda-common/gda-error.c:135
#, c-format
msgid "%s: An Error occured in the CORBA system."
msgstr "%s: CORBA システムでエラーが発生しました"

#: lib/gda-common/gda-error.c:152
#, fuzzy
msgid "[CORBA User Exception]"
msgstr "CORBA ユーザ例外: %s"

#: lib/gda-common/gda-error.c:201
msgid "Unknown CORBA exception for connection"
msgstr ""

#: lib/gda-common/gda-init.c:55
msgid "Attempt to initialize an already initialized client"
msgstr "初期化を試みましたがすでにクライアントは初期化されています"

#: lib/gda-common/gda-init.c:64 lib/gda-server/gda-server-init.c:121
#, fuzzy
msgid "Could not initialize Bonobo"
msgstr "ct_diag() を初期化することが出来ませんでした"

#: lib/gda-common/gda-log.c:48
msgid "Saving log...x"
msgstr "ログを保存中...x"

#. compose message
#: lib/gda-common/gda-log.c:68
msgid "ERROR: "
msgstr "エラー: "

#: lib/gda-common/gda-log.c:68
msgid "MESSAGE: "
msgstr "メッセージ: "

#: lib/gda-common/gda-thread.c:168
msgid "thread is already running"
msgstr "スレッドはすでに実行中です"

#: lib/gda-common/gda-util.c:113
#, fuzzy, c-format
msgid "Could not open file %s"
msgstr "'%s' にロケールを設定することが出来ませんでした"

#: lib/gda-common/gda-util.c:138
#, fuzzy, c-format
msgid "Could not create file %s"
msgstr "フィールドを割り当てることが出来ませんでした"

#: lib/gda-common/gda-xml-database.c:166
msgid "bad formed document"
msgstr ""

#: lib/gda-common/gda-xml-database.c:267
#, c-format
msgid "table %s already exists"
msgstr "テーブル %s はすでに存在しています"

#: lib/gda-common/gda-xml-database.c:449
#, c-format
msgid "%p is not a valid table"
msgstr "%p は有効なテーブルではありません"

#: lib/gda-common/gda-xml-item.c:385
#, fuzzy, c-format
msgid "Item with id %s not found"
msgstr "データソース %s は見つかりませんでした"

#: lib/gda-server/gda-server-connection.c:404
#, fuzzy
msgid "Connection being closed"
msgstr "接続は切れたようです"

#: lib/gda-server/gda-server-connection.c:407
msgid "This connection is being closed, so all listeners are released"
msgstr ""

#: lib/gda-server/gda-server-error.c:41
msgid "Could not get pointer to server implementation"
msgstr "サーバの実装へのポインタを取得することが出来ませんでした"

#: lib/gda-server/gda-server-init.c:43 lib/gda-server/gda-server-init.c:49
#, c-format
msgid "Received signal %d, shutting down"
msgstr "シグナル %d を受信しました, 終了します"

#: lib/gda-server/gda-server-init.c:53
#, c-format
msgid "Received signal %d. Ignoring"
msgstr "シグナル %d を受信しました, 無視します"

#: lib/gda-server/gda-server-init.c:104
msgid "Attempt to initialize an already initialized provider"
msgstr "初期化を試みましたがすでにプロバイダは初期化されています"

#: lib/gda-server/gda-server-recordset.c:52
#: lib/gda-server/gda-server-recordset.c:60
#: lib/gda-server/gda-server-recordset.c:100
#: lib/gda-server/gda-server-recordset.c:108
#, c-format
msgid "%s not implemented"
msgstr "%s は実装されていません"

#: lib/gda-server/gda-server.c:128
#, c-format
msgid "Starting provider %s with no implementation functions"
msgstr "未実装の機能をプロバイダ %s で開始しています"

#: lib/gda-server/gda-server.c:214
#, c-format
msgid "CORBA system exception %s"
msgstr "CORBA システム例外 %s"

#: lib/gda-server/gda-server.c:218
#, c-format
msgid "CORBA user exception: %s"
msgstr "CORBA ユーザ例外: %s"

#: providers/gda-default-server/GNOME_GDA_Provider_Default.oaf.in.h:1
#, fuzzy
msgid "Default provider connection factory"
msgstr "%s へ接続することが出来ませんでした"

#: providers/gda-default-server/GNOME_GDA_Provider_Default.oaf.in.h:2
#, fuzzy
msgid "GDA Default Datasource Access"
msgstr "ODBC用のGDAデータソースアクセス"

#: providers/gda-default-server/gda-default-connection.c:127
msgid "You must specify a directory for the database to be stored"
msgstr ""

#: providers/gda-default-server/gda-default-connection.c:235
#: providers/gda-mysql-server/gda-mysql-connection.c:282
#: providers/gda-oracle-server/gda-oracle-connection.c:334
#: providers/gda-postgres-server/gda-postgres-connection.c:486
#, fuzzy
msgid "Unknown schema type"
msgstr "未知の ORACLE タイプ %ld です"

#: providers/gda-default-server/main-default.c:69
#, fuzzy
msgid "Could not register Default provider implementation"
msgstr "メールプロバイダの実装を登録することが出来ませんでした"

#: providers/gda-ldap-server/GNOME_GDA_Provider_LDAP.oaf.in.h:1
msgid "GDA Datasource Access for LDAP"
msgstr "LDAP用のGDAデータソースアクセス"

#: providers/gda-ldap-server/GNOME_GDA_Provider_LDAP.oaf.in.h:2
msgid "LDAP provider connection factory"
msgstr ""

#: providers/gda-interbase-server/gda-interbase-connection.c:288
#: providers/gda-ldap-server/gda-ldap-connection.c:293
#: providers/gda-mdb-server/gda-mdb-connection.c:372
#: providers/gda-mysql-server/gda-mysql-connection.c:486
#: providers/gda-odbc-server/gda-odbc-connection.c:624
#: providers/gda-odbc-server/gda-odbc-connection.c:657
#: providers/gda-oracle-server/gda-oracle-connection.c:479
#: providers/gda-postgres-server/gda-postgres-connection.c:767
#: providers/gda-sybase-server/gda-sybase-error.c:132
#: providers/gda-tds-server/gda-tds-error.c:123
#, c-format
msgid "error '%s' at %s"
msgstr "エラー '%s' が %s で発生しました"

#. gda_error_set_help_file (error, _("Not available"));
#: providers/gda-interbase-server/gda-interbase-connection.c:294
#: providers/gda-ldap-server/gda-ldap-connection.c:298
#: providers/gda-ldap-server/gda-ldap-connection.c:299
#: providers/gda-mdb-server/gda-mdb-connection.c:377
#: providers/gda-mysql-server/gda-mysql-connection.c:491
#: providers/gda-mysql-server/gda-mysql-connection.c:492
#: providers/gda-odbc-server/gda-odbc-connection.c:626
#: providers/gda-odbc-server/gda-odbc-connection.c:628
#: providers/gda-odbc-server/gda-odbc-connection.c:659
#: providers/gda-odbc-server/gda-odbc-connection.c:661
#: providers/gda-oracle-server/gda-oracle-connection.c:484
#: providers/gda-oracle-server/gda-oracle-connection.c:485
#: providers/gda-postgres-server/gda-postgres-connection.c:775
#: providers/gda-postgres-server/gda-postgres-connection.c:776
#: providers/gda-primebase-server/gda-primebase-connection.c:375
#: providers/gda-primebase-server/gda-primebase-connection.c:376
#: providers/gda-sybase-server/gda-sybase-error.c:142
#: providers/gda-tds-server/gda-tds-error.c:132
#: providers/gda-tds-server/gda-tds-error.c:133
msgid "Not available"
msgstr "利用できません"

#: providers/gda-interbase-server/gda-interbase-connection.c:295
#: providers/gda-ldap-server/gda-ldap-connection.c:300
#: providers/gda-mdb-server/gda-mdb-connection.c:378
#: providers/gda-mysql-server/gda-mysql-connection.c:493
#: providers/gda-oracle-server/gda-oracle-connection.c:486
#: providers/gda-postgres-server/gda-postgres-connection.c:777
#: providers/gda-primebase-server/gda-primebase-connection.c:377
#: providers/gda-sybase-server/gda-sybase-error.c:143
#: providers/gda-tds-server/gda-tds-error.c:134
msgid "error"
msgstr "エラー"

#: providers/gda-ldap-server/main-ldap.c:73
msgid "Could not register LDAP provider implementation"
msgstr "LDAP プロバイダの実装を登録することが出来ませんでした"

#: providers/gda-interbase-server/GNOME_GDA_Provider_InterBase.oaf.in.h:1
msgid "GDA Datasource Access for Interbase"
msgstr "Interbase用のGDAデータソースアクセス"

#: providers/gda-interbase-server/GNOME_GDA_Provider_InterBase.oaf.in.h:2
msgid "InterBase provider connection factory"
msgstr ""

#: providers/gda-interbase-server/gda-interbase-connection.c:286
#, c-format
msgid "Error code %ld"
msgstr "エラーコード %ld"

#: providers/gda-interbase-server/main-interbase.c:74
msgid "Could not register INTERBASE provider implementation"
msgstr "INTERBASE プロバイダの実装を登録することが出来ませんでした"

#: providers/gda-mail-server/GNOME_GDA_Provider_Mail.oaf.in.h:1
msgid "GDA Datasource Access for Mail"
msgstr "Mail用のGDAデータソースアクセス"

#: providers/gda-mail-server/GNOME_GDA_Provider_Mail.oaf.in.h:2
msgid "Mail provider connection factory"
msgstr ""

#: providers/gda-mail-server/gda-mail-connection.c:107
#: providers/gda-mdb-server/gda-mdb-connection.c:224
#: providers/gda-sybase-server/gda-sybase-connection.c:290
#: providers/gda-tds-server/gda-tds-connection.c:278
#, c-format
msgid "Unhandled SCHEMA_QTYPE %d"
msgstr "SCHEMA_QTYPE %d は扱えません"

#: providers/gda-mail-server/main-mail.c:74
msgid "Could not register Mail provider implementation"
msgstr "メールプロバイダの実装を登録することが出来ませんでした"

#: providers/gda-mdb-server/GNOME_GDA_Provider_MDB.oaf.in.h:1
msgid "GDA Datasource Access for MDB (MS Access) files"
msgstr "MDB (MS Access)ファイル用のGDAデータソースアクセス"

#: providers/gda-mdb-server/GNOME_GDA_Provider_MDB.oaf.in.h:2
msgid "MDB provider connection factory"
msgstr ""

#. execute command
#: providers/gda-mdb-server/gda-mdb-command.c:86
#: providers/gda-mysql-server/gda-mysql-command.c:144
#: providers/gda-sybase-server/gda-sybase-command.c:141
#: providers/gda-tds-server/gda-tds-command.c:120
#, c-format
msgid "executing command '%s'"
msgstr "コマンド '%s' を実行しています"

#: providers/gda-mdb-server/gda-mdb-command.c:88
#: providers/gda-mysql-server/gda-mysql-command.c:149
#, c-format
msgid "info '%s'"
msgstr "情報 '%s'"

#: providers/gda-mdb-server/gda-mdb-connection.c:137
#, c-format
msgid ""
"%s:%d: You cannot provide a UNIX_SOCKET if you also provide either a HOST or "
"a PORT. Please remove the UNIX_SOCKET, or remove both the HOST and PORT "
"options"
msgstr ""
"%s:%d: UNIX_SOCKET を提供することが出来ません. HOST または PORT のどちらかを"
"提供するなら, UNIX_SOCKET を削除するか, HOST と PORT の両方のオプションを削除"
"してください"

#: providers/gda-mdb-server/gda-mdb-connection.c:147
#, c-format
msgid "%s:%d: You must  provide the filename with the MS Access database"
msgstr "%s:%d: MS Access データベースのファイル名を提供しなければなりません"

#: providers/gda-mdb-server/gda-mdb-connection.c:152
#, c-format
msgid "Opening connection with filename=%s, user=%s, password=%s"
msgstr "ファイル名=%s, ユーザ=%s, パスワード=%s で接続を開いています"

#: providers/gda-mdb-server/gda-mdb-connection.c:427
msgid "mysql_recset is NULL"
msgstr "mysql_recset は NULL です"

#: providers/gda-mdb-server/gda-mdb-connection.c:469
#: providers/gda-mysql-server/gda-mysql-connection.c:838
#: providers/gda-sybase-server/gda-sybase-connection.c:469
#: providers/gda-tds-server/gda-tds-connection.c:448
msgid "No table name given for SCHEMA_COLS"
msgstr "SCHEMA_COLS のためのテーブル名が与えられていません"

#: providers/gda-mdb-server/main-mdb.c:72
#: providers/gda-mysql-server/main-mysql.c:74
msgid "Could not register MySQL provider implementation"
msgstr "MySQL プロバイダの実装を登録することが出来ませんでした"

#: providers/gda-mysql-server/GNOME_GDA_Provider_MySQL.oaf.in.h:1
msgid "GDA Datasource Access for MySQL"
msgstr "MySQL用のGDAデータソースアクセス"

#: providers/gda-mysql-server/GNOME_GDA_Provider_MySQL.oaf.in.h:2
msgid "MySQL provider connection factory"
msgstr ""

#: providers/gda-mysql-server/gda-mysql-connection.c:174
#, fuzzy
msgid ""
"You cannot provide a UNIX_SOCKET if you also provide either a HOST or a "
"PORT. Please remove the UNIX_SOCKET, or remove both the HOST and PORT options"
msgstr ""
"%s:%d: UNIX_SOCKET を提供することが出来ません. HOST または PORT のどちらかを"
"提供するなら, UNIX_SOCKET を削除するか, HOST と PORT の両方のオプションを削除"
"してください"

#: providers/gda-mysql-server/gda-mysql-connection.c:190
#, c-format
msgid ""
"Opening connection with user=%s, password=%s, host=%s, port=%s, unix_socket=%"
"s"
msgstr ""
"ユーザ=%s, パスワード=%s, ホスト=%s, ポート=%s, unix ソケット=%s で接続を開い"
"ています"

#: providers/gda-mysql-server/gda-mysql-connection.c:616
msgid "Unknown"
msgstr ""

#: providers/gda-mysql-server/gda-mysql-connection.c:649
msgid "No MYSQL_Connection for GdaServerConnection"
msgstr ""

#: providers/gda-odbc-server/GNOME_GDA_Provider_ODBC.oaf.in.h:1
msgid "GDA Datasource Access for ODBC"
msgstr "ODBC用のGDAデータソースアクセス"

#: providers/gda-odbc-server/GNOME_GDA_Provider_ODBC.oaf.in.h:2
msgid "ODBC provider connection factory"
msgstr ""

#: providers/gda-odbc-server/gda-odbc-connection.c:277
#, c-format
msgid "gda_odbc_connection_open_schema: Unhandled SCHEMA_QTYPE %d\n"
msgstr "gda_odbc_connection_open_schema: SCHEMA_QTYPE %d は扱えません\n"

#: providers/gda-odbc-server/gda-odbc-connection.c:641
#: providers/gda-odbc-server/gda-odbc-connection.c:642
#: providers/gda-odbc-server/gda-odbc-connection.c:643
#: providers/gda-odbc-server/gda-odbc-connection.c:674
#: providers/gda-odbc-server/gda-odbc-connection.c:675
#: providers/gda-odbc-server/gda-odbc-connection.c:676
msgid "no text"
msgstr "テキストがありません"

#: providers/gda-odbc-server/main-odbc.c:73
msgid "Could not register ODBC provider implementation"
msgstr "ODBC プロバイダの実装を登録することが出来ませんでした"

#: providers/gda-oracle-server/GNOME_GDA_Provider_Oracle.oaf.in.h:1
msgid "GDA Datasource Access for Oracle"
msgstr "Oracle用のGDAデータソースアクセス"

#: providers/gda-oracle-server/GNOME_GDA_Provider_Oracle.oaf.in.h:2
msgid "Oracle provider connection factory"
msgstr ""

#: providers/gda-oracle-server/gda-oracle-command.c:191
msgid "Could not allocate statement handle"
msgstr "ステートメントハンドルを割り当てることが出来ませんでした"

#: providers/gda-oracle-server/gda-oracle-command.c:197
msgid "command object being created without associated connection"
msgstr "コマンドオブジェクトは接続なしで作成しました"

#: providers/gda-oracle-server/gda-oracle-command.c:238
#, c-format
msgid "Executing command '%s'"
msgstr "コマンド '%s' を実行しています"

#: providers/gda-oracle-server/gda-oracle-connection.c:117
msgid "error in OCIHandleAlloc() HTYPE_SVCCTX"
msgstr "OCIHandleAlloc() HTYPE_SVCCTX でエラーが発生しました"

#: providers/gda-oracle-server/gda-oracle-connection.c:123
msgid "error in OCIHandleAlloc() HTYPE_SERVER"
msgstr "OCIHandleAlloc() HTYPE_SERVER でエラーが発生しました"

#: providers/gda-oracle-server/gda-oracle-connection.c:129
msgid "error in OCIHandleAlloc() HTYPE_ERROR"
msgstr "OCIHandleAlloc() HTYPE_ERROR でエラーが発生しました"

#: providers/gda-oracle-server/gda-oracle-connection.c:418
#, c-format
msgid "Unknown ORACLE type %ld"
msgstr "未知の ORACLE タイプ %ld です"

#: providers/gda-oracle-server/gda-oracle-recordset.c:118
msgid "Unknown ORACLE data type in fill_field_values"
msgstr "fill_field_values に未知の ORACLE データタイプがあります"

#: providers/gda-oracle-server/gda-oracle-recordset.c:156
msgid "recordset object being created without associated connection"
msgstr "レコードセットオブジェクトは接続なしで作成しました"

#: providers/gda-oracle-server/main-oracle.c:69
msgid "Could not register ORACLE provider implementation"
msgstr "ORACLE プロバイダの実装を登録することが出来ませんでした"

#: providers/gda-postgres-server/GNOME_GDA_Provider_Postgres.oaf.in.h:1
msgid "GDA Datasource Access for Postgres"
msgstr "Postgres用のGDAデータソースアクセス"

#: providers/gda-postgres-server/GNOME_GDA_Provider_Postgres.oaf.in.h:2
msgid "Postgres provider connection factory"
msgstr ""

#: providers/gda-postgres-server/gda-postgres-connection.c:888
#: providers/gda-postgres-server/gda-postgres-connection.c:1005
msgid "postgres_recset is NULL"
msgstr "postgres_recset は NULL です"

#: providers/gda-postgres-server/main-postgres.c:71
msgid "Could not register PostgreSQL provider implementation"
msgstr "PostgreSQL プロバイダの実装を登録することが出来ませんでした"

#: providers/gda-sybase-server/GNOME_GDA_Provider_Sybase.oaf.in.h:1
msgid "GDA Datasource Access for Sybase"
msgstr "Sybase用のGDAデータソースアクセス"

#: providers/gda-sybase-server/GNOME_GDA_Provider_Sybase.oaf.in.h:2
msgid "Sybase provider connection factory"
msgstr ""

#.      gda_server_error_make(error, 0, cnc, "connection seems to be dead");
#: providers/gda-sybase-server/gda-sybase-command.c:136
#: providers/gda-tds-server/gda-tds-command.c:116
msgid "Connection seems to be dead"
msgstr "接続は切れたようです"

#: providers/gda-sybase-server/gda-sybase-command.c:153
#: providers/gda-tds-server/gda-tds-command.c:130
msgid "Filling command structure failed\n"
msgstr "コマンド構造体の充填に失敗しました\n"

#: providers/gda-sybase-server/gda-sybase-command.c:162
#: providers/gda-tds-server/gda-tds-command.c:137
msgid "sending cmd failed"
msgstr "コマンドの送信に失敗しました"

#: providers/gda-sybase-server/gda-sybase-command.c:169
#: providers/gda-tds-server/gda-tds-command.c:144
msgid "Allocating recordset failed"
msgstr "レコードセットの割り当てに失敗しました"

#: providers/gda-sybase-server/gda-sybase-command.c:181
#: providers/gda-tds-server/gda-tds-command.c:153
msgid "Getting recordset userdata failed"
msgstr "レコードセットのユーザデータの取得に失敗しました"

#: providers/gda-sybase-server/gda-sybase-command.c:241
#: providers/gda-tds-server/gda-tds-command.c:210
msgid "Command execution finished, all results processed"
msgstr "コマンドの実行は完了しました, すべての結果を処理しました"

#: providers/gda-sybase-server/gda-sybase-command.c:245
#: providers/gda-tds-server/gda-tds-command.c:214
msgid "Command failed"
msgstr "コマンドは失敗しました"

#: providers/gda-sybase-server/gda-sybase-command.c:250
#: providers/gda-tds-server/gda-tds-command.c:219
msgid "Execution of resultless command succeeded"
msgstr "結果のない実行コマンドは成功しました"

#: providers/gda-sybase-server/gda-sybase-command.c:268
#: providers/gda-tds-server/gda-tds-command.c:237
#, c-format
msgid "ct_results() returned %x"
msgstr "ct_results() は %x を返しました"

#: providers/gda-sybase-server/gda-sybase-command.c:280
#: providers/gda-tds-server/gda-tds-command.c:249
msgid "No further results, command completly succeeded."
msgstr "深刻な結果はありません, コマンドは完全に成功しました"

#: providers/gda-sybase-server/gda-sybase-command.c:285
#: providers/gda-tds-server/gda-tds-command.c:254
msgid "An error occured during command execution."
msgstr "コマンド実行中にエラーが発生しました"

#: providers/gda-sybase-server/gda-sybase-command.c:291
#: providers/gda-tds-server/gda-tds-command.c:258
msgid "Cmd execution returned unknown result, may be an error"
msgstr "コマンド実行は未知の結果を返しました, エラーかもしれません"

#: providers/gda-sybase-server/gda-sybase-command.c:304
#: providers/gda-tds-server/gda-tds-command.c:269
msgid "No data returned, freeing recordset structure"
msgstr "データが返されません, レコードセット構造体を開放しています"

#: providers/gda-sybase-server/gda-sybase-command.c:336
#: providers/gda-sybase-server/gda-sybase-command.c:348
#: providers/gda-tds-server/gda-tds-command.c:300
#: providers/gda-tds-server/gda-tds-command.c:310
msgid "Freeing command structure failed"
msgstr "コマンド構造体の開放に失敗しました"

#: providers/gda-sybase-server/gda-sybase-connection.c:176
#, fuzzy
msgid "Not enough memory for sybase_Connection"
msgstr "primebase_Error 構造体のための十分なメモリがありません"

#: providers/gda-sybase-server/gda-sybase-connection.c:458
#: providers/gda-tds-server/gda-tds-connection.c:437
#, c-format
msgid "schema_cols: table_name '%s'"
msgstr "schema_cols: table_name '%s'"

#: providers/gda-sybase-server/gda-sybase-connection.c:475
#: providers/gda-tds-server/gda-tds-connection.c:454
msgid "Could not allocate command structure"
msgstr "コマンド構造体を割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:498
#: providers/gda-tds-server/gda-tds-connection.c:477
msgid "Could not allocate enough memory for query"
msgstr "クエリのための十分なメモリを割り当てることが出来ませんでした"

#.          gda_server_error_make(error, NULL, cnc, __PRETTY_FUNCTION__);
#: providers/gda-sybase-server/gda-sybase-connection.c:513
#: providers/gda-tds-server/gda-tds-connection.c:492
msgid "Could not get recordset in schema_cols"
msgstr "schema_cols からレコードセットを取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:562
#: providers/gda-tds-server/gda-tds-connection.c:541
#, c-format
msgid "schema_procs: invalid constraint type %d"
msgstr "schema_procs: 制約タイプ %d は無効です"

#: providers/gda-sybase-server/gda-sybase-connection.c:572
#: providers/gda-tds-server/gda-tds-connection.c:551
msgid "Could not allocate cmd structure"
msgstr "コマンド構造体を割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:638
#: providers/gda-tds-server/gda-tds-connection.c:617
#, c-format
msgid "schema_tables: invalid constraint type %d"
msgstr "schema_tables: 制約タイプ %d は無効です"

#: providers/gda-sybase-server/gda-sybase-connection.c:700
#: providers/gda-tds-server/gda-tds-connection.c:679
#, c-format
msgid "Invalid or unsupported constraint type: %d"
msgstr "制約タイプは無効またはサポートしていません: %d"

#: providers/gda-sybase-server/gda-sybase-connection.c:743
#: providers/gda-tds-server/gda-tds-connection.c:722
msgid "Could not allocate GdaServerCommand"
msgstr "GdaServerCommand の割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:774
#: providers/gda-sybase-server/gda-sybase-connection.c:779
#: providers/gda-tds-server/gda-tds-connection.c:752
#: providers/gda-tds-server/gda-tds-connection.c:757
#, c-format
msgid "connection status: %x"
msgstr "接続状況: %x"

#: providers/gda-sybase-server/gda-sybase-connection.c:775
#: providers/gda-tds-server/gda-tds-connection.c:753
#, c-format
msgid "return code: %x"
msgstr "戻り値: %x"

#: providers/gda-sybase-server/gda-sybase-connection.c:813
#: providers/gda-tds-server/gda-tds-connection.c:788
msgid "attempting reconnection"
msgstr "再接続を試みています"

#: providers/gda-sybase-server/gda-sybase-connection.c:943
#, c-format
msgid "Reconnected to '%s'"
msgstr "'%s' へ再接続しました"

#: providers/gda-sybase-server/gda-sybase-connection.c:945
#: providers/gda-tds-server/gda-tds-connection.c:890
#, c-format
msgid "Connected to %s"
msgstr "%s に接続完了"

#: providers/gda-sybase-server/gda-sybase-connection.c:957
#: providers/gda-tds-server/gda-tds-connection.c:904
#, c-format
msgid "Selected database '%s'"
msgstr "データベース '%s' を選択しました"

#: providers/gda-sybase-server/gda-sybase-connection.c:986
#: providers/gda-tds-server/gda-tds-connection.c:930
#, c-format
msgid "%s: Could not allocate cmd structure"
msgstr "%s: コマンド構造体を割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:995
#: providers/gda-tds-server/gda-tds-connection.c:939
#, c-format
msgid "%s: Could not allocate memory for cmd string"
msgstr "%s: コマンド文字列のためのメモリを割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:1004
#: providers/gda-tds-server/gda-tds-connection.c:947
#, c-format
msgid "%s: ct_command failed"
msgstr "%s: ct_command は失敗しました"

#: providers/gda-sybase-server/gda-sybase-connection.c:1015
#: providers/gda-tds-server/gda-tds-connection.c:957
#, c-format
msgid "%s: sending command failed"
msgstr "%s: コマンドの送信は失敗しました"

#: providers/gda-sybase-server/gda-sybase-connection.c:1026
#, c-format
msgid "%s: selecting database failed"
msgstr "%s: データベースの選択に失敗しました"

#: providers/gda-sybase-server/gda-sybase-connection.c:1043
#, c-format
msgid "%s: use command failed"
msgstr "%s: ユーザコマンドは失敗しました"

#: providers/gda-sybase-server/gda-sybase-connection.c:1071
#: providers/gda-tds-server/gda-tds-connection.c:1020
msgid "Could not allocate locale structure"
msgstr "ロケール構造体を割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:1077
#: providers/gda-tds-server/gda-tds-connection.c:1026
#, c-format
msgid "Could not set locale to '%s'"
msgstr "'%s' にロケールを設定することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:1084
#: providers/gda-tds-server/gda-tds-connection.c:1033
#, c-format
msgid "Could not configure locale to be '%s'"
msgstr "'%s' にロケールを設定することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:1090
#: providers/gda-tds-server/gda-tds-connection.c:1039
msgid "Could not drop locale structure"
msgstr "ロケール構造体をドロップすることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:1104
#: providers/gda-tds-server/gda-tds-connection.c:1052
#, c-format
msgid "Fatal error: %s\n"
msgstr "致命的なエラー: %s\n"

#: providers/gda-sybase-server/gda-sybase-error.c:78
#, c-format
msgid "gda_sybase_error_make(%p,%p,%p,%p)"
msgstr "gda_sybase_error_make(%p,%p,%p,%p)"

#: providers/gda-sybase-server/gda-sybase-error.c:90
#: providers/gda-tds-server/gda-tds-error.c:81
#, c-format
msgid "No error flag ist set, though %s is called. This may be a bug."
msgstr ""
"%s が呼ばれたにもかかわらずエラーフラグが設定されていません. これは不具合かも"
"しれません"

#: providers/gda-sybase-server/gda-sybase-error.c:166
msgid "cs_diag() initialized"
msgstr "cs_diag() を初期化しました"

#: providers/gda-sybase-server/gda-sybase-error.c:170
msgid "Could not initialize cs_diag()"
msgstr "cs_diag() を初期化することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:180
msgid "ct_diag() initialized"
msgstr "ct_diag() を初期化しました"

#: providers/gda-sybase-server/gda-sybase-error.c:184
msgid "Could not initialize ct_diag()"
msgstr "ct_diag() を初期化することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:220
#, c-format
msgid "%s could not find server implementation"
msgstr "%s をサーバの実装から見付けることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:227
#, c-format
msgid "%s could not get cnc userdata"
msgstr "%s は cnc ユーザデータを取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:239
msgid "Could not get # of messages"
msgstr "メッセージ数を取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:246
#, c-format
msgid "%d ctlib messages to fetch"
msgstr "%d 個の ctlib メッセージを取得しました"

#: providers/gda-sybase-server/gda-sybase-error.c:251
#, c-format
msgid "%d ctlib message to fetch"
msgstr "%d 個の ctlib メッセージを取得しました"

#: providers/gda-sybase-server/gda-sybase-error.c:289
msgid "error is nullpointer in gda_sybase_messages_handle"
msgstr "gda_sybase_messages_handle の NULL ポインタはエラーです"

#: providers/gda-sybase-server/gda-sybase-error.c:315
#: providers/gda-sybase-server/gda-sybase-error.c:387
#: providers/gda-sybase-server/gda-sybase-error.c:434
msgid "Could not get # of server messages"
msgstr "サーバメッセージ数を取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:323
#, c-format
msgid "Fetching %d client messages"
msgstr "%d 個のクライアントメッセージを取得しています"

#: providers/gda-sybase-server/gda-sybase-error.c:326
#, c-format
msgid "Fetching %d client message"
msgstr "%d 個のクライアントメッセージを取得しています"

#: providers/gda-sybase-server/gda-sybase-error.c:335
#, c-format
msgid "Could not get client msg # %d"
msgstr "クライアントメッセージ番号 %d を取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:354
msgid "Could not get # of client messages"
msgstr "クライアントメッセージ数を取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:362
msgid "Could not clear client messages"
msgstr "クライアントメッセージを消去することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:395
#, c-format
msgid "Fetching %d server messages"
msgstr "%d 個のサーバメッセージを取得しています"

#: providers/gda-sybase-server/gda-sybase-error.c:398
#, c-format
msgid "Fetching %d server message"
msgstr "%d 個のサーバメッセージを取得しています"

#: providers/gda-sybase-server/gda-sybase-error.c:407
#, c-format
msgid "Could not get server msg # %d"
msgstr "サーバメッセージ番号 %d を取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:442
msgid "Could not clear server messages"
msgstr "サーバメッセージを消去することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:464
#: providers/gda-sybase-server/gda-sybase-error.c:504
msgid "Could not get # of cslib messages"
msgstr "cslib メッセージ数を取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:472
#, c-format
msgid "Fetching %d cslib messages"
msgstr "%d 個の cslib メッセージを取得してします"

#: providers/gda-sybase-server/gda-sybase-error.c:475
#, c-format
msgid "Fetching %d cslib message"
msgstr "%d 個の cslib メッセージを取得してします"

#: providers/gda-sybase-server/gda-sybase-error.c:485
#, c-format
msgid "Could not get cslib msg # %d"
msgstr "cslib メッセージ番号 %d を取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:512
msgid "Could not clear cslib messages"
msgstr "cslib メッセージを消去することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:646
#: providers/gda-tds-server/gda-tds-error.c:269
msgid "Server message:"
msgstr "サーバメッセージ:"

#: providers/gda-sybase-server/gda-sybase-error.c:654
#: providers/gda-tds-server/gda-tds-error.c:277
msgid "Client message:"
msgstr "クライアントメッセージ:"

#: providers/gda-sybase-server/gda-sybase-error.c:661
#: providers/gda-tds-server/gda-tds-error.c:284
msgid "CS-Library error:"
msgstr "CS-Library エラー:"

#: providers/gda-sybase-server/gda-sybase-recordset.c:203
#: providers/gda-tds-server/gda-tds-recordset.c:194
#, c-format
msgid "fetch error at row %d"
msgstr "%d 列目の取得でエラーが発生しました"

#: providers/gda-sybase-server/gda-sybase-recordset.c:210
#: providers/gda-tds-server/gda-tds-recordset.c:201
#, c-format
msgid "CS_END_DATA on row %d; canceling"
msgstr "%d 列目で CS_END_DATA; キャンセル中"

#: providers/gda-sybase-server/gda-sybase-recordset.c:218
#: providers/gda-tds-server/gda-tds-recordset.c:208
#, c-format
msgid "%s: Error (%d)"
msgstr "%s: エラー (%d)"

#: providers/gda-sybase-server/gda-sybase-recordset.c:391
#: providers/gda-tds-server/gda-tds-recordset.c:382
msgid "Failed fetching # of columns"
msgstr "カラム数の取得に失敗しました"

#: providers/gda-sybase-server/gda-sybase-recordset.c:398
#: providers/gda-tds-server/gda-tds-recordset.c:390
#, c-format
msgid "Counted %d columns"
msgstr "%d カラムをカウントしました"

#: providers/gda-sybase-server/gda-sybase-recordset.c:405
#: providers/gda-tds-server/gda-tds-recordset.c:397
#, c-format
msgid "%s could not allocate datafmt info"
msgstr "%s はデータフォーマット情報を割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-recordset.c:415
#: providers/gda-tds-server/gda-tds-recordset.c:407
#, c-format
msgid "%s could not allocate data fields"
msgstr "%s はデータフィールドを割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-recordset.c:433
#: providers/gda-tds-server/gda-tds-recordset.c:425
#, c-format
msgid "ct_describe on col # %d"
msgstr "カラム番号 %d で ct_describe します"

#: providers/gda-sybase-server/gda-sybase-recordset.c:440
#: providers/gda-tds-server/gda-tds-recordset.c:432
#, c-format
msgid "ct_describe on col # %d failed"
msgstr "カラム番号 %d で ct_describe に失敗しました"

#: providers/gda-sybase-server/gda-sybase-recordset.c:447
#: providers/gda-tds-server/gda-tds-recordset.c:439
#, c-format
msgid "ct_describe(%d): '%s', %d (%s)"
msgstr "ct_describe(%d): '%s', %d (%s)"

#: providers/gda-sybase-server/gda-sybase-recordset.c:459
#: providers/gda-tds-server/gda-tds-recordset.c:450
msgid "could not allocate data holder"
msgstr "データホルダーを割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-recordset.c:472
#: providers/gda-tds-server/gda-tds-recordset.c:463
msgid "could not ct_bind data holder to column"
msgstr "カラムにデータホルダーを ct_bind することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-recordset.c:479
#: providers/gda-tds-server/gda-tds-recordset.c:470
msgid "illegal type detected, aborting"
msgstr "不当なタイプを検出しました, 中止しています"

#: providers/gda-sybase-server/gda-sybase-recordset.c:486
#: providers/gda-tds-server/gda-tds-recordset.c:477
msgid "could not allocate field"
msgstr "フィールドを割り当てることが出来ませんでした"

#: providers/gda-sybase-server/main-sybase.c:78
msgid "Could not register gda-sybase provider implementation"
msgstr "gda-sybase プロバイダの実装を登録することが出来ませんでした"

#: providers/gda-primebase-server/GNOME_GDA_Provider_Primebase.oaf.in.h:1
msgid "GDA Datasource Access for primebase"
msgstr "primebase用のGDAデータソースアクセス"

#: providers/gda-primebase-server/gda-primebase-connection.c:157
#, c-format
msgid "Could not connect to '%s@%s:%s' with connparm '%s'"
msgstr "'%s@%s:%s'へ接続パラメータ '%s'で接続することが出来ませんでした"

#: providers/gda-primebase-server/gda-primebase-connection.c:163
#, c-format
msgid "%2ld: Connected to '%s@%s:%s' with connparm: '%s'"
msgstr "%2ld: '%s@%s:%s'へ接続パラメータ '%s'で接続しました"

#: providers/gda-primebase-server/gda-primebase-connection.c:171
msgid "Could not get PBIConnectionInfo(), disconnecting"
msgstr "PBIConnectionInfo() を得ることが出来ませんでした, 切断しています"

#: providers/gda-primebase-server/gda-primebase-connection.c:176
#, c-format
msgid "%2ld: ConInfo: '%s@%s', Cl v%x, Srv '%s' v%x, Brand '%s'"
msgstr "%2ld: ConInfo: '%s@%s', Cl v%x, Srv '%s' v%x, Brand '%s'"

#: providers/gda-primebase-server/gda-primebase-connection.c:390
msgid "Not enough memory for primebase_Error structure."
msgstr "primebase_Error 構造体のための十分なメモリがありません"

#: providers/gda-primebase-server/gda-primebase-connection.c:397
#, c-format
msgid "%2ld: ERROR: %ld (%ld) : %s.\n"
msgstr "%2ld: エラー: %ld (%ld) : %s.\n"

#: providers/gda-primebase-server/main-primebase.c:73
msgid "Could not register PRIMEBASE provider implementation"
msgstr "PRIMEBASE プロバイダの実装を登録することが出来ませんでした"

#: providers/gda-tds-server/GNOME_GDA_Provider_TDS.oaf.in.h:1
msgid "GDA Datasource Access for Sybase/MS SQL"
msgstr "Sybase/MS SQL用のGDAデータソースアクセス"

#: providers/gda-tds-server/GNOME_GDA_Provider_TDS.oaf.in.h:2
msgid "TDS provider connection factory"
msgstr ""

#: providers/gda-tds-server/gda-tds-connection.c:160
#, fuzzy
msgid "Not enough memory for tds_Connection"
msgstr "primebase_Error 構造体のための十分なメモリがありません"

#. Fixme: replace "dummy" with buf when CS_GET CS_SERVERNAME works
#: providers/gda-tds-server/gda-tds-connection.c:888
#, c-format
msgid "Reconnected to %s"
msgstr "'%s' へ再接続しました"

#: providers/gda-tds-server/gda-tds-error.c:70
#, c-format
msgid "gda_tds_error_make(%p,%p,%p,%p)"
msgstr "gda_tds_error_make(%p,%p,%p,%p)"

#: providers/gda-tds-server/main-tds.c:78
msgid "Could not register gda-tds provider implementation"
msgstr "gda-tds プロバイダの実装を登録することが出来ませんでした"

#: tools/gda-run.c:109
#, c-format
msgid "%s: misconfigured DSN entry"
msgstr "%s: DSN エントリの設定ミスです"

#: tools/gda-run.c:124
#, c-format
msgid "%s: data source '%s' not found\n"
msgstr "%s: データソース '%s' は見つかりませんでした\n"

#: tools/templates/main-srv.c.tmpl:60
#, fuzzy
msgid "Could not register <PROVIDER-NAME> provider implementation"
msgstr "PRIMEBASE プロバイダの実装を登録することが出来ませんでした"

#~ msgid "impl_GDA_Connection_open: opening connection with DSN: %s"
#~ msgstr "impl_GDA_Connection_open: DSN '%s' で接続を開いています"

#~ msgid "%s: an error ocurred while fetching data"
#~ msgstr "%s: データ取得中にエラーが発生しました"

#~ msgid ""
#~ "OAF doesn't know about our IID; indicates broken installation. Exiting..."
#~ msgstr ""
#~ "OAF は IID について知りません; インストールが失敗しているかもれません. 終"
#~ "了します..."

#~ msgid ""
#~ "Another instance of this provider is already registered with OAF. "
#~ "Exiting..."
#~ msgstr ""
#~ "このプロバイダの別のインスタンスはすでに OAF が登録しています. 終了しま"
#~ "す..."

#~ msgid "Unknown error registering this provider with OAF. Exiting"
#~ msgstr ""
#~ "OAF がこのプロバイダを登録中に未知のエラーが発生しました. 終了します"

#~ msgid "Registered with ID = %s"
#~ msgstr "ID = %s で登録しました"

#~ msgid "CORBA exception unloading report engine: %s"
#~ msgstr "CORBA 例外はレポートエンジンを取り外しています: %s"

#~ msgid "GDA Distributed Report Engine"
#~ msgstr "GDA分配レポートエンジン"

#~ msgid "Received signal %d, shutting down."
#~ msgstr "シグナル %d を受信しました, 終了します"

#~ msgid "Received signal %d, shutting down cleanly"
#~ msgstr "シグナル %d を受信しました, きれいに終了します"

#~ msgid "Failed to initialize OAF: please mail bug report to OAF maintainers"
#~ msgstr "OAF の初期化に失敗: OAF メンテナへ不具合報告をメールしてください"

#~ msgid "Could not activate report engine"
#~ msgstr "レポートエンジンを始動させることが出来ませんでした"

#~ msgid ""
#~ "Another instance of the report engine is already registered with OAF. "
#~ "Exiting..."
#~ msgstr ""
#~ "レポートエンジンの別のインスタンスはすでに OAF が登録しています. 終了しま"
#~ "す..."

#~ msgid "Unknown error registering report engine with OAF. Exiting"
#~ msgstr ""
#~ "OAF がレポートエンジンを登録中に未知のエラーが発生しました. 終了します"

#~ msgid "Registered report engine with ID = %s"
#~ msgstr "ID = %s でレポートエンジンを登録しました"

#~ msgid "%s: length = %d"
#~ msgstr "%s: 長さ = %d"

#~ msgid "%s: sending field description for '%s'"
#~ msgstr "%s: '%s' のためのフィールドの記述を送信中"

#~ msgid "schema_tables: table name = '%s'"
#~ msgstr "schema_tables: テーブル名 = '%s'"

#~ msgid "schema_tables: table_schema = '%s'"
#~ msgstr "schema_tables: table_schema = '%s'"

#~ msgid "schema_procedures: proc_catalog = '%s' UNUSED!\n"
#~ msgstr "schema_procedures: proc_catalog = %s' は使っていません!\n"

#~ msgid "schema_procedures: proc_catalog = '%s' UNUSED!"
#~ msgstr "schema_procedures: proc_catalog = '%s' は使っていません!"

#~ msgid "database name"
#~ msgstr "データベース名"

#~ msgid "DATABASE"
#~ msgstr "DATABASE"

#~ msgid "user name"
#~ msgstr "ユーザ名"

#~ msgid "USER-NAME"
#~ msgstr "USER-NAME"

#~ msgid "password"
#~ msgstr "パスワード"

#~ msgid "PASSWORD"
#~ msgstr "PASSWORD"

#~ msgid "file name"
#~ msgstr "ファイル名"

#~ msgid "FILE-NAME"
#~ msgstr "FILE-NAME"
