# Copyright (C) 1999 Free Software Foundation, Inc.
# Valek Filippov <frob@df.ru>, 1999.
#
msgid ""
msgstr ""
"Project-Id-Version: gnome-db\n"
"POT-Creation-Date: 2000-11-30 14:13+0300\n"
"PO-Revision-Date: 2000-11-30 14:26+03:00\n"
"Last-Translator: Valek Filippov <frob@df.ru>\n"
"Language-Team: Russian <ru@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=koi8-r\n"
"Content-Transfer-Encoding: 8-bit\n"

# fe/fe_editor.c:175 fe/fe_editor.c:212
#: lib/gda-client/gda-connection-pool.c:266
#, c-format
msgid "could not open connection to %s"
msgstr "не удалось открыть соединение с %s"

# fe/fe_main.c:205
#: lib/gda-client/gda-connection-pool.c:279
#, c-format
msgid "Data source %s not found"
msgstr "Не найден источник данных %s"

#: lib/gda-client/gda-connection.c:233 lib/gda-client/gda-error.c:178
#, c-format
msgid "%s: The server didn't respond."
msgstr "%s: Сервер не отвечает."

#: lib/gda-client/gda-connection.c:237 lib/gda-client/gda-error.c:182
#, c-format
msgid "%s: An Error occured in the CORBA system."
msgstr "%s: Возникла ошибка в системе CORBA."

#: lib/gda-client/gda-connection.c:528
#, c-format
msgid "Database '%s' not found in system configuration"
msgstr "База данных '%s' не найдена в конфигурации системы"

#: lib/gda-client/gda-connection.c:544
msgid "Could not open CORBA factory"
msgstr ""

# gda-clnt/gda-field.c:95
#: lib/gda-client/gda-field.c:244
msgid "<NULL>"
msgstr "<NULL>"

# gda-clnt/gda-field.c:101 gda-clnt/gda-field.c:103
#: lib/gda-client/gda-field.c:250 lib/gda-client/gda-field.c:252
msgid "<Unknown GDA Type(NULL)>"
msgstr "<Неизвестный GDA тип(NULL)>"

# gda-clnt/gda-field.c:117
#: lib/gda-client/gda-field.c:265
msgid "TRUE"
msgstr "ИСТИНА"

# gda-clnt/gda-field.c:119
#: lib/gda-client/gda-field.c:266
msgid "FALSE"
msgstr "ЛОЖЬ"

#: lib/gda-common/gda-corba.c:76
#, c-format
msgid "CORBA System exception: %s"
msgstr "Исключение системы CORBA: %s"

#: lib/gda-common/gda-corba.c:109
msgid "True"
msgstr "Истина"

# fe/fe_main.c:249
#: lib/gda-common/gda-corba.c:109
msgid "False"
msgstr "Ложь"

#: lib/gda-common/gda-init.c:58
msgid "Attempt to initialize an already initialized client"
msgstr "Попытка инициализировать уже инициализированного клиента"

#: lib/gda-common/gda-log.c:47
msgid "Saving log...x"
msgstr "Сохранение журнала...x"

#. compose message
#: lib/gda-common/gda-log.c:68
msgid "ERROR: "
msgstr "ОШИБКА:"

#: lib/gda-common/gda-log.c:68
msgid "MESSAGE: "
msgstr "СООБЩЕНИЕ:"

#: lib/gda-common/gda-thread.c:210
msgid "thread is already running"
msgstr "thread уже запущен"

#: lib/gda-common/gda-xml-database.c:281
#, c-format
msgid "table %s already exists"
msgstr "таблица %s уже существует"

#: lib/gda-common/gda-xml-database.c:445
#, c-format
msgid "%p is not a valid table"
msgstr "%p не является допустимой таблицей"

#: lib/gda-server/gda-server-error.c:185
msgid "Could not get pointer to server implementation"
msgstr "Невозможно получить указатель на реализацию сервера"

#: lib/gda-server/gda-server-impl-connection.c:122
#: lib/gda-server/gda-server-impl-connection.c:131
#: lib/gda-server/gda-server-impl-connection.c:138
#: lib/gda-server/gda-server-impl-connection.c:147
#: lib/gda-server/gda-server-impl-connection.c:154
#: lib/gda-server/gda-server-impl-connection.c:163
#: lib/gda-server/gda-server-impl-connection.c:170
#: lib/gda-server/gda-server-impl-connection.c:179
#: lib/gda-server/gda-server-impl-recordset.c:125
#: lib/gda-server/gda-server-impl-recordset.c:134
#: lib/gda-server/gda-server-impl-recordset.c:141
#: lib/gda-server/gda-server-impl-recordset.c:156
#: lib/gda-server/gda-server-impl-recordset.c:165
#: lib/gda-server/gda-server-impl-recordset.c:172
#: lib/gda-server/gda-server-impl-recordset.c:181
#: lib/gda-server/gda-server-impl-recordset.c:188
#: lib/gda-server/gda-server-impl-recordset.c:197
#: lib/gda-server/gda-server-impl-recordset.c:204
#: lib/gda-server/gda-server-impl-recordset.c:212
#: lib/gda-server/gda-server-impl-recordset.c:221
#: lib/gda-server/gda-server-impl-recordset.c:228
#: lib/gda-server/gda-server-impl-recordset.c:236
#: lib/gda-server/gda-server-impl-recordset.c:244
#: lib/gda-server/gda-server-impl-recordset.c:272
#: lib/gda-server/gda-server-impl-recordset.c:280
#: lib/gda-server/gda-server-impl-recordset.c:288
#: lib/gda-server/gda-server-impl-recordset.c:296
#: lib/gda-server/gda-server-impl-recordset.c:304
#: lib/gda-server/gda-server-impl-recordset.c:313
#, c-format
msgid "%s not implemented"
msgstr "%s не реализовано"

#: lib/gda-server/gda-server-impl-connection.c:271
#, c-format
msgid "impl_GDA_Connection_open: opening connection with DSN: %s"
msgstr "impl_GDA_Connection_open: открытие соединения с DSN: %s"

#: lib/gda-server/gda-server-impl-recordset.c:406
#, c-format
msgid "%s: an error ocurred while fetching data"
msgstr "%s: обнаружена ошибка при получении данных"

#: lib/gda-server/gda-server-impl-recordset.c:445
#, c-format
msgid "%s: length = %d"
msgstr "%s: длина = %d"

#: lib/gda-server/gda-server-impl-recordset.c:458
#, c-format
msgid "%s: sending field description for '%s'"
msgstr "%s: послано описание поля для \"%s\""

#: lib/gda-server/gda-server-impl.c:194
#, c-format
msgid "Starting provider %s with no implementation functions"
msgstr "Запуск провайдера %s с не реализованными функциями"

#: lib/gda-server/gda-server-impl.c:221
#: report/server/gda-report-server-main.c:120
msgid ""
"OAF doesn't know about our IID; indicates broken installation. Exiting..."
msgstr ""
"OAF не знает о нашем IID; указывает на неправильную установку. Выход..."

#: lib/gda-server/gda-server-impl.c:224
msgid ""
"Another instance of this provider is already registered with OAF. Exiting..."
msgstr "Другой экземпляр этого провайдера уже зарегистрирован в OAF. Выход..."

#: lib/gda-server/gda-server-impl.c:227
msgid "Unknown error registering this provider with OAF. Exiting"
msgstr "Неизвестная ошибка регистрации этого провайдера в OAF. Выход"

#: lib/gda-server/gda-server-impl.c:231
#, c-format
msgid "Registered with ID = %s"
msgstr "Зарегистрировано с идентификатором = %s"

#: lib/gda-server/gda-server-impl.c:313
#, c-format
msgid "CORBA system exception %s"
msgstr "Исключение системы CORBA %s"

#: lib/gda-server/gda-server-impl.c:316
#, c-format
msgid "CORBA user exception: %s"
msgstr "Исключение пользователя CORBA %s"

#: lib/gda-server/gda-server-init.c:62 lib/gda-server/gda-server-init.c:68
#, c-format
msgid "Received signal %d, shutting down"
msgstr "Получен сигнал %d, выключение"

#: lib/gda-server/gda-server-init.c:72
#, c-format
msgid "Received signal %d. Ignoring"
msgstr "Получен сигнал %d. Игнорируется"

#: lib/gda-server/gda-server-init.c:122
msgid "Attempt to initialize an already initialized provider"
msgstr "Попытка инициализации уже инициализированного провайдера"

#: providers/gda-interbase-server/gda-interbase-connection.c:252
#: providers/gda-ldap-server/gda-ldap-connection.c:263
#: providers/gda-mdb-server/gda-mdb-connection.c:351
#: providers/gda-mysql-server/gda-mysql-connection.c:378
#: providers/gda-odbc-server/gda-odbc-connection.c:600
#: providers/gda-odbc-server/gda-odbc-connection.c:633
#: providers/gda-oracle-server/gda-oracle-connection.c:417
#: providers/gda-postgres-server/gda-postgres-connection.c:771
#: providers/gda-sybase-server/gda-sybase-error.c:106
#, c-format
msgid "error '%s' at %s"
msgstr "ошибка '%s' в %s"

#: providers/gda-interbase-server/gda-interbase-connection.c:257
#: providers/gda-interbase-server/gda-interbase-connection.c:258
#: providers/gda-ldap-server/gda-ldap-connection.c:268
#: providers/gda-ldap-server/gda-ldap-connection.c:269
#: providers/gda-mdb-server/gda-mdb-connection.c:355
#: providers/gda-mdb-server/gda-mdb-connection.c:356
#: providers/gda-mysql-server/gda-mysql-connection.c:382
#: providers/gda-mysql-server/gda-mysql-connection.c:383
#: providers/gda-odbc-server/gda-odbc-connection.c:602
#: providers/gda-odbc-server/gda-odbc-connection.c:603
#: providers/gda-odbc-server/gda-odbc-connection.c:635
#: providers/gda-odbc-server/gda-odbc-connection.c:636
#: providers/gda-oracle-server/gda-oracle-connection.c:422
#: providers/gda-oracle-server/gda-oracle-connection.c:423
#: providers/gda-postgres-server/gda-postgres-connection.c:778
#: providers/gda-postgres-server/gda-postgres-connection.c:779
#: providers/gda-sybase-server/gda-sybase-error.c:115
#: providers/gda-sybase-server/gda-sybase-error.c:116
msgid "Not available"
msgstr "Не доступно"

#: providers/gda-interbase-server/gda-interbase-connection.c:259
#: providers/gda-ldap-server/gda-ldap-connection.c:270
#: providers/gda-mdb-server/gda-mdb-connection.c:357
#: providers/gda-mysql-server/gda-mysql-connection.c:384
#: providers/gda-oracle-server/gda-oracle-connection.c:424
#: providers/gda-postgres-server/gda-postgres-connection.c:780
#: providers/gda-sybase-server/gda-sybase-error.c:117
msgid "error"
msgstr "ошибка"

#: providers/gda-ldap-server/main-ldap.c:68
msgid "Could not register LDAP provider implementation"
msgstr "Не удалось зарегистрировать реализацию провайдера LDAP"

#: providers/gda-interbase-server/gda-interbase-connection.c:251
#, c-format
msgid "Error code %ld"
msgstr "Код ошибки %ld"

#: providers/gda-interbase-server/main-interbase.c:69
msgid "Could not register INTERBASE provider implementation"
msgstr "Не удалось зарегистрировать реализацию провайдера INTERBASE"

#: providers/gda-mail-server/gda-mail-connection.c:108
#: providers/gda-mdb-server/gda-mdb-connection.c:224
#: providers/gda-mysql-server/gda-mysql-connection.c:251
#: providers/gda-oracle-server/gda-oracle-connection.c:295
#: providers/gda-postgres-server/gda-postgres-connection.c:511
#: providers/gda-sybase-server/gda-sybase-connection.c:259
#, c-format
msgid "Unhandled SCHEMA_QTYPE %d"
msgstr "Необработанный SCHEMA_QTYPE %d"

#: providers/gda-mail-server/main-mail.c:69
msgid "Could not register Mail provider implementation"
msgstr "Не удалось зарегистрировать реализацию провайдера Mail"

# fe/fe_editor.c:185
#. execute command
#: providers/gda-mdb-server/gda-mdb-command.c:86
#: providers/gda-mysql-server/gda-mysql-command.c:87
#: providers/gda-sybase-server/gda-sybase-command.c:120
#, c-format
msgid "executing command '%s'"
msgstr "выполнение команды \"%s\""

# fe/fe_editor.c:185
#: providers/gda-mdb-server/gda-mdb-command.c:88
#: providers/gda-mysql-server/gda-mysql-command.c:89
#, c-format
msgid "info '%s'"
msgstr "информация \"%s\""

#: providers/gda-mdb-server/gda-mdb-connection.c:137
#: providers/gda-mysql-server/gda-mysql-connection.c:148
#, c-format
msgid ""
"%s:%d: You cannot provide a UNIX_SOCKET if you also provide either a HOST or "
"a PORT. Please remove the UNIX_SOCKET, or remove both the HOST and PORT "
"options"
msgstr ""
"%s:%d: Вы не можете указывать UNIX_SOCKET, если вы также указываете Хост или "
"Порт. Пожалуйста удалить параметры Хост и Порт или UNIX_SOCKET"

#: providers/gda-mdb-server/gda-mdb-connection.c:147
#, c-format
msgid "%s:%d: You must  provide the filename with the MS Access database"
msgstr "%s:%d: Вы должны ввести имя файла базы данных MS Access"

#: providers/gda-mdb-server/gda-mdb-connection.c:152
#, c-format
msgid "Opening connection with filename=%s, user=%s, password=%s"
msgstr ""
"Открытие соединения с параметрами имя_файла=%s, пользователь=%s, пароль=%s"

#: providers/gda-mdb-server/gda-mdb-connection.c:406
#: providers/gda-mysql-server/gda-mysql-connection.c:433
msgid "mysql_recset is NULL"
msgstr "mysql_recset имеет значение NULL"

#: providers/gda-mdb-server/gda-mdb-connection.c:448
#: providers/gda-mysql-server/gda-mysql-connection.c:475
#: providers/gda-sybase-server/gda-sybase-connection.c:413
msgid "No table name given for SCHEMA_COLS"
msgstr "Не задано название таблицы для SCHEMA_COLS"

#: providers/gda-mdb-server/main-mdb.c:69
#: providers/gda-mysql-server/main-mysql.c:69
msgid "Could not register MySQL provider implementation"
msgstr "Не удалось зарегистрировать реализацию провайдера MySQL"

#: providers/gda-mysql-server/gda-mysql-connection.c:162
#, c-format
msgid ""
"Opening connection with user=%s, password=%s, host=%s, port=%s, "
"unix_socket=%s"
msgstr ""
"Открытие соединения с параметрами пользователь=%s, пароль=%s, хост=%s, "
"порт=%s, unix_socket=%s"

#: providers/gda-odbc-server/gda-odbc-connection.c:280
#, c-format
msgid "gda_odbc_connection_open_schema: Unhandled SCHEMA_QTYPE %d\n"
msgstr "gda_odbc_connection_open_schema: необработанный SCHEMA_QTYPE %d\n"

#: providers/gda-odbc-server/gda-odbc-connection.c:617
#: providers/gda-odbc-server/gda-odbc-connection.c:618
#: providers/gda-odbc-server/gda-odbc-connection.c:619
#: providers/gda-odbc-server/gda-odbc-connection.c:650
#: providers/gda-odbc-server/gda-odbc-connection.c:651
#: providers/gda-odbc-server/gda-odbc-connection.c:652
msgid "no text"
msgstr "нет текста"

#: providers/gda-odbc-server/main-odbc.c:68
msgid "Could not register ODBC provider implementation"
msgstr "Не удалось зарегистрировать реализацию провайдера ODBC"

# fe/fe_log.c:92
#: providers/gda-oracle-server/gda-oracle-command.c:195
msgid "Could not allocate statement handle"
msgstr "Не удалось получить обработчик утверждения"

#: providers/gda-oracle-server/gda-oracle-command.c:199
msgid "command object being created without associated connection"
msgstr "командный объект был создан без ассоциированного соединения"

# fe/fe_editor.c:185
#: providers/gda-oracle-server/gda-oracle-command.c:226
#, c-format
msgid "Executing command '%s'"
msgstr "Выполнение команды \"%s\""

#: providers/gda-oracle-server/gda-oracle-connection.c:113
msgid "error in OCIHandleAlloc() HTYPE_SVCCTX"
msgstr "ошибка в OCIHandleAlloc() HTYPE_SVCCTX"

#: providers/gda-oracle-server/gda-oracle-connection.c:116
msgid "error in OCIHandleAlloc() HTYPE_SERVER"
msgstr "ошибка в OCIHandleAlloc() HTYPE_SERVER"

#: providers/gda-oracle-server/gda-oracle-connection.c:119
msgid "error in OCIHandleAlloc() HTYPE_ERROR"
msgstr "ошибка в OCIHandleAlloc() HTYPE_ERROR"

#: providers/gda-oracle-server/gda-oracle-connection.c:370
#, c-format
msgid "Unknown ORACLE type %ld"
msgstr "Неизвестный тип ORACLE %ld"

#: providers/gda-oracle-server/gda-oracle-recordset.c:115
msgid "Unknown ORACLE data type in fill_field_values"
msgstr "Неизвестный ORACLE тип данных в fill_field_values"

#: providers/gda-oracle-server/gda-oracle-recordset.c:150
msgid "recordset object being created without associated connection"
msgstr "объект recordset был создан без ассоциированного соединения"

#: providers/gda-oracle-server/main-oracle.c:68
msgid "Could not register ORACLE provider implementation"
msgstr "Не удалось зарегистрировать реализацию провайдера ORACLE"

#: providers/gda-postgres-server/gda-postgres-connection.c:880
#: providers/gda-postgres-server/gda-postgres-connection.c:992
msgid "postgres_recset is NULL"
msgstr "postgres_recset имеет значение NULL"

#: providers/gda-postgres-server/main-postgres.c:68
msgid "Could not register PostgreSQL provider implementation"
msgstr "Не удалось зарегистрировать реализацию провайдера PostgreSQL"

#: providers/gda-sybase-server/gda-sybase-command.c:115
msgid "Connection seems to be dead"
msgstr "Видимо соединение умерло"

#: providers/gda-sybase-server/gda-sybase-command.c:135
msgid "Filling command structure failed\n"
msgstr "Сбой заполнения управляющей структуры\n"

#: providers/gda-sybase-server/gda-sybase-command.c:147
msgid "sending cmd failed"
msgstr "сбой отправки кмд"

#: providers/gda-sybase-server/gda-sybase-command.c:154
msgid "Allocating recordset failed"
msgstr ""

#: providers/gda-sybase-server/gda-sybase-command.c:164
msgid "Getting recordset userdata failed"
msgstr ""

#: providers/gda-sybase-server/gda-sybase-command.c:222
msgid "Command execution finished, all results processed"
msgstr "Выполнение команды завершено, все результаты обрабатываются"

# fe/fe_editor.c:138
#: providers/gda-sybase-server/gda-sybase-command.c:226
msgid "Command failed"
msgstr "Выполнение команды не удалось"

#: providers/gda-sybase-server/gda-sybase-command.c:230
msgid "Execution of resultless command succeeded"
msgstr "Выполнение \"безрезультатной\" команды прошло успешно"

#: providers/gda-sybase-server/gda-sybase-command.c:246
#, c-format
msgid "ct_results() returned %x"
msgstr ""

#: providers/gda-sybase-server/gda-sybase-command.c:256
msgid "No further results, command completly succeeded."
msgstr "Нет последующих результатов, команда выполнена успешно."

#: providers/gda-sybase-server/gda-sybase-command.c:260
msgid "An error occured during command execution."
msgstr "При выполнении команды возникла ошибка."

#: providers/gda-sybase-server/gda-sybase-command.c:267
msgid "Cmd execution returned unknown result, may be an error"
msgstr "Выполнение команды привело к неизвестному результату, возможно к ошибке"

#: providers/gda-sybase-server/gda-sybase-command.c:280
msgid "No data returned, freeing recordset structure"
msgstr ""

#: providers/gda-sybase-server/gda-sybase-command.c:311
#: providers/gda-sybase-server/gda-sybase-command.c:323
msgid "Freeing command structure failed"
msgstr "Сбой освобождения структуры команды"

#: providers/gda-sybase-server/gda-sybase-connection.c:139
msgid "Error allocating error structure"
msgstr "Ошибка получения структуры ошибки"

#: providers/gda-sybase-server/gda-sybase-connection.c:147
msgid "Not enough memory for sybase_Connection"
msgstr "Недостаточно памяти для выполнения sybase_Соединения"

#: providers/gda-sybase-server/gda-sybase-connection.c:403
#, c-format
msgid "schema_cols: table_name '%s'"
msgstr ""

# fe/fe_log.c:92
#: providers/gda-sybase-server/gda-sybase-connection.c:419
msgid "Could not allocate command structure"
msgstr "Не удалось получить структуру команды"

# fe/fe_log.c:92
#: providers/gda-sybase-server/gda-sybase-connection.c:441
msgid "Could not allocate enough memory for query"
msgstr "Не удалось получить достаточно памяти для запроса"

#: providers/gda-sybase-server/gda-sybase-connection.c:455
msgid "Could not get recordset in schema_cols"
msgstr ""

#: providers/gda-sybase-server/gda-sybase-connection.c:487
#: providers/gda-sybase-server/gda-sybase-connection.c:564
#, c-format
msgid "schema_tables: table name = '%s'"
msgstr ""

#: providers/gda-sybase-server/gda-sybase-connection.c:495
#: providers/gda-sybase-server/gda-sybase-connection.c:572
#, c-format
msgid "schema_tables: table_schema = '%s'"
msgstr ""

#: providers/gda-sybase-server/gda-sybase-connection.c:500
#, c-format
msgid "schema_procedures: proc_catalog = '%s' UNUSED!\n"
msgstr ""

#: providers/gda-sybase-server/gda-sybase-connection.c:504
#, c-format
msgid "schema_procs: invalid constraint type %d"
msgstr ""

# fe/fe_log.c:92
#: providers/gda-sybase-server/gda-sybase-connection.c:514
msgid "Could not allocate cmd structure"
msgstr "Не удалось получить структуру кмд"

#: providers/gda-sybase-server/gda-sybase-connection.c:577
#, c-format
msgid "schema_procedures: proc_catalog = '%s' UNUSED!"
msgstr ""

#: providers/gda-sybase-server/gda-sybase-connection.c:581
#, c-format
msgid "schema_tables: invalid constraint type %d"
msgstr ""

#: providers/gda-sybase-server/gda-sybase-connection.c:642
#, c-format
msgid "Invalid or unsupported constraint type: %d"
msgstr "Неправильный или неподдерживаемый тип ограничения: %d"

# fe/fe_log.c:92
#: providers/gda-sybase-server/gda-sybase-connection.c:683
msgid "Could not allocate Gda_ServerCommand"
msgstr "Не удалось получить Gda_ServerCommand"

#: providers/gda-sybase-server/gda-sybase-connection.c:713
#: providers/gda-sybase-server/gda-sybase-connection.c:718
#, c-format
msgid "connection status: %x"
msgstr "состояние соединения: %x"

#: providers/gda-sybase-server/gda-sybase-connection.c:714
#, c-format
msgid "return code: %x"
msgstr "код возврата: %x"

# fe/fe_connection.c:88
#: providers/gda-sybase-server/gda-sybase-connection.c:751
msgid "attempting reconnection"
msgstr "попытка пересоединения"

# fe/fe_connection.c:46
#: providers/gda-sybase-server/gda-sybase-connection.c:890
#, c-format
msgid "Reconnected to '%s'"
msgstr "Пересоединение с \"%s\""

# fe/fe_connection.c:46
#: providers/gda-sybase-server/gda-sybase-connection.c:892
#, c-format
msgid "Connected to %s"
msgstr "Соединен с %s"

# fe/fe_designer.c:40
#: providers/gda-sybase-server/gda-sybase-connection.c:900
#, c-format
msgid "Selected database '%s'"
msgstr "Выбранная база данных \"%s\""

# fe/fe_log.c:92
#: providers/gda-sybase-server/gda-sybase-connection.c:929
#, c-format
msgid "%s: Could not allocate cmd structure"
msgstr "%s: Не удалось получить структуру кмд"

#: providers/gda-sybase-server/gda-sybase-connection.c:938
#, c-format
msgid "%s: Could not allocate memory for cmd string"
msgstr "%s: Не удалось получить память для строки кмд"

# fe/fe_editor.c:138
#: providers/gda-sybase-server/gda-sybase-connection.c:951
#, c-format
msgid "%s: ct_command failed"
msgstr "%s: сбой ct_command"

# fe/fe_editor.c:138
#: providers/gda-sybase-server/gda-sybase-connection.c:960
#, c-format
msgid "%s: sending command failed"
msgstr "%s: отправка команды не удалась"

#: providers/gda-sybase-server/gda-sybase-connection.c:971
#, c-format
msgid "%s: selecting database failed"
msgstr "%s: сбой выбора базы данных"

# fe/fe_editor.c:138
#: providers/gda-sybase-server/gda-sybase-connection.c:989
#, c-format
msgid "%s: use command failed"
msgstr "%s: сбой использования команды"

# fe/fe_log.c:92
#: providers/gda-sybase-server/gda-sybase-connection.c:1016
msgid "Could not allocate locale structure"
msgstr "Не удалось получить структуру locale"

# fe/fe_editor.c:175 fe/fe_editor.c:212
#: providers/gda-sybase-server/gda-sybase-connection.c:1022
#, c-format
msgid "Could not set locale to '%s'"
msgstr "Не удалось установить локализацию для '%s'"

# fe/fe_editor.c:175 fe/fe_editor.c:212
#: providers/gda-sybase-server/gda-sybase-connection.c:1028
#, c-format
msgid "Could not configure locale to be '%s'"
msgstr "Не удалось настроить локализацию на '%s'"

# fe/fe_editor.c:175 fe/fe_editor.c:212
#: providers/gda-sybase-server/gda-sybase-connection.c:1033
msgid "Could not drop locale structure"
msgstr "Не удалось сбросить структуру locale"

#: providers/gda-sybase-server/gda-sybase-connection.c:1046
#, c-format
msgid "Fatal error: %s\n"
msgstr "Фатальная ошибка: %s\n"

#: providers/gda-sybase-server/gda-sybase-error.c:62
#, c-format
msgid "gda_sybase_error_make(%p,%p,%p,%p)"
msgstr "gda_sybase_error_make(%p,%p,%p,%p)"

#: providers/gda-sybase-server/gda-sybase-error.c:71
#, c-format
msgid "No error flag ist set, though %s is called. This may be a bug."
msgstr ""

#: providers/gda-sybase-server/gda-sybase-error.c:135
msgid "cs_diag() initialized"
msgstr "cs_diag() инициализовано"

#: providers/gda-sybase-server/gda-sybase-error.c:138
msgid "Could not initialize cs_diag()"
msgstr "Не удалось инициализировать cs_diag()"

#: providers/gda-sybase-server/gda-sybase-error.c:145
msgid "ct_diag() initialized"
msgstr "ct_diag() инициализовано"

#: providers/gda-sybase-server/gda-sybase-error.c:148
msgid "Could not initialize ct_diag()"
msgstr "Не удалось инициализировать ct_diag()"

#: providers/gda-sybase-server/gda-sybase-error.c:182
#, c-format
msgid "%s could not find server implementation"
msgstr "%s невозможно найти реализацию сервера"

#: providers/gda-sybase-server/gda-sybase-error.c:188
#, c-format
msgid "%s could not get cnc userdata"
msgstr ""

#: providers/gda-sybase-server/gda-sybase-error.c:200
msgid "Could not get # of messages"
msgstr "Не удалось получит число сообщений"

#: providers/gda-sybase-server/gda-sybase-error.c:205
#, c-format
msgid "%d ctlib messages to fetch"
msgstr ""

#: providers/gda-sybase-server/gda-sybase-error.c:207
#, c-format
msgid "%d ctlib message to fetch"
msgstr ""

#: providers/gda-sybase-server/gda-sybase-error.c:243
msgid "error is nullpointer in gda_sybase_messages_handle"
msgstr ""

#: providers/gda-sybase-server/gda-sybase-error.c:268
#: providers/gda-sybase-server/gda-sybase-error.c:335
#: providers/gda-sybase-server/gda-sybase-error.c:378
msgid "Could not get # of server messages"
msgstr "Невозможно получить номер сообщения сервера"

#: providers/gda-sybase-server/gda-sybase-error.c:276
#, c-format
msgid "Fetching %d client messages"
msgstr "Получение %d клиентских сообщений"

#: providers/gda-sybase-server/gda-sybase-error.c:278
#, c-format
msgid "Fetching %d client message"
msgstr "Получение %d клиентского сообщения"

#: providers/gda-sybase-server/gda-sybase-error.c:287
#, c-format
msgid "Could not get client msg # %d"
msgstr "Не удалось получить клиентское сообщение # %d"

#: providers/gda-sybase-server/gda-sybase-error.c:303
msgid "Could not get # of client messages"
msgstr "Не удалось получить число клиентских сообщений"

# fe/fe_editor.c:175 fe/fe_editor.c:212
#: providers/gda-sybase-server/gda-sybase-error.c:311
msgid "Could not clear client messages"
msgstr "Не удалось очистить клиентские сообщения"

#: providers/gda-sybase-server/gda-sybase-error.c:343
#, c-format
msgid "Fetching %d server messages"
msgstr "Получение %d серверных сообщений"

#: providers/gda-sybase-server/gda-sybase-error.c:345
#, c-format
msgid "Fetching %d server message"
msgstr "Получение %d серверного сообщения"

# fe/fe_log.c:92
#: providers/gda-sybase-server/gda-sybase-error.c:354
#, c-format
msgid "Could not get server msg # %d"
msgstr "Не удалось получить серверное сообщение # %d"

# fe/fe_log.c:92
#: providers/gda-sybase-server/gda-sybase-error.c:386
msgid "Could not clear server messages"
msgstr "Не удалось очистить серверные сообщения"

#: providers/gda-sybase-server/gda-sybase-error.c:408
#: providers/gda-sybase-server/gda-sybase-error.c:444
msgid "Could not get # of cslib messages"
msgstr "Не удалось получить число сообщений cslib"

#: providers/gda-sybase-server/gda-sybase-error.c:416
#, c-format
msgid "Fetching %d cslib messages"
msgstr "Получение %d сообщений cslib"

#: providers/gda-sybase-server/gda-sybase-error.c:418
#, c-format
msgid "Fetchong %d cslib message"
msgstr "Получение %d сообщения cslib"

#: providers/gda-sybase-server/gda-sybase-error.c:428
#, c-format
msgid "Could not get cslib msg # %d"
msgstr "Не удалось получить сообщение cslib # %d"

#: providers/gda-sybase-server/gda-sybase-error.c:452
msgid "Could not clear cslib messages"
msgstr "Не удалось очистить сообщения cslib"

#: providers/gda-sybase-server/gda-sybase-error.c:584
msgid "Server message:"
msgstr "Сообщение сервера:"

#: providers/gda-sybase-server/gda-sybase-error.c:593
msgid "Client message:"
msgstr "Сообщение клиента:"

#: providers/gda-sybase-server/gda-sybase-error.c:600
msgid "CS-Library error:"
msgstr "Ошибка CS-библиотеки:"

#: providers/gda-sybase-server/gda-sybase-recordset.c:152
#, c-format
msgid "fetch error at row %d"
msgstr "получена ошибка в строке %d"

#: providers/gda-sybase-server/gda-sybase-recordset.c:159
#, c-format
msgid "CS_END_DATA on row %d; canceling"
msgstr "CS_END_DATA в строке %d; отмена"

#: providers/gda-sybase-server/gda-sybase-recordset.c:168
#, c-format
msgid "%s: Error (%d)"
msgstr "%s: Ошибка (%d)"

#: providers/gda-sybase-server/gda-sybase-recordset.c:343
msgid "Failed fetching # of columns"
msgstr "Сбой получения числа столбцов"

#: providers/gda-sybase-server/gda-sybase-recordset.c:349
#, c-format
msgid "Counted %d columns"
msgstr "Подсчитано %d столбцов"

# fe/fe_log.c:92
#: providers/gda-sybase-server/gda-sybase-recordset.c:356
#, fuzzy, c-format
msgid "%s could not allocate datafmt info"
msgstr "Не удалось получить обработчик утверждения"

# fe/fe_log.c:92
#: providers/gda-sybase-server/gda-sybase-recordset.c:366
#, c-format
msgid "%s could not allocate data fields"
msgstr "%s Не удалось получить поля данных"

#: providers/gda-sybase-server/gda-sybase-recordset.c:384
#, c-format
msgid "ct_describe on col # %d"
msgstr ""

#: providers/gda-sybase-server/gda-sybase-recordset.c:391
#, c-format
msgid "ct_describe on col # %d failed"
msgstr ""

#: providers/gda-sybase-server/gda-sybase-recordset.c:397
#, c-format
msgid "ct_describe(%d): '%s', %d (%s)"
msgstr ""

# fe/fe_log.c:92
#: providers/gda-sybase-server/gda-sybase-recordset.c:406
#, fuzzy
msgid "could not allocate data holder"
msgstr "Не удалось получить обработчик утверждения"

#: providers/gda-sybase-server/gda-sybase-recordset.c:416
msgid "could not ct_bind data holder to column"
msgstr ""

#: providers/gda-sybase-server/gda-sybase-recordset.c:423
msgid "illegal type detected, aborting"
msgstr "обнаружен недопустимый тип, прерывание"

# fe/fe_log.c:92
#: providers/gda-sybase-server/gda-sybase-recordset.c:429
msgid "could not allocate field"
msgstr "не удалось получить поле"

#: providers/gda-sybase-server/main-sybase.c:73
msgid "Could not register gda-sybase provider implementation"
msgstr "Не удалось зарегистрировать реализацию провайдера gda-sybase"

#: report/gda-report-engine.c:87
#, c-format
msgid "CORBA exception unloading report engine: %s"
msgstr ""

#: report/server/gda-report-server-main.c:43
#: report/server/gda-report-server-main.c:50
#, c-format
msgid "Received signal %d, shutting down."
msgstr "Получен сигнал %d, выключение."

#: report/server/gda-report-server-main.c:54
#, c-format
msgid "Received signal %d, shutting down cleanly"
msgstr "Получен сигнал %d, чистое выключение"

#: report/server/gda-report-server-main.c:96
msgid "Failed to initialize OAF: please mail bug report to OAF maintainers"
msgstr "Сбой инициализации OAF: пожалуйста, отправьте сообщение об ошибке разработчикам OAF"

# fe/fe_log.c:92
#: report/server/gda-report-server-main.c:106
#, fuzzy
msgid "Could not activate report engine"
msgstr "Не удалось активировать сервис %s"

#: report/server/gda-report-server-main.c:123
#, fuzzy
msgid ""
"Another instance of the report engine is already registered with OAF. "
"Exiting..."
msgstr "Другой экземпляр этого провайдера уже зарегистрирован в OAF. Выход..."

#: report/server/gda-report-server-main.c:126
#, fuzzy
msgid "Unknown error registering report engine with OAF. Exiting"
msgstr "Неизвестная ошибка регистрации этого провайдера в OAF. Выход"

#: report/server/gda-report-server-main.c:130
#, fuzzy, c-format
msgid "Registered report engine with ID = %s"
msgstr "Зарегистрировано с идентификатором = %s"

# fe/fe_main.c:186
#: tools/gda-run.c:30
msgid "database name"
msgstr "название базы данных"

#: tools/gda-run.c:30
msgid "DATABASE"
msgstr "БАЗА ДАННЫХ"

# fe/fe_impexp.c:164 fe/fe_impexp.c:274 fe/fe_impexp.c:391
# gda-clnt-ui/gnome-db-browser.c:217
#: tools/gda-run.c:31
msgid "user name"
msgstr "имя пользователя"

#: tools/gda-run.c:31
msgid "USER-NAME"
msgstr "ИМЯ ПОЛЬЗОВАТЕЛЯ"

#: tools/gda-run.c:32
msgid "password"
msgstr "пароль"

#: tools/gda-run.c:32
msgid "PASSWORD"
msgstr "ПАРОЛЬ"

# fe/fe_impexp.c:164 fe/fe_impexp.c:274 fe/fe_impexp.c:391
# gda-clnt-ui/gnome-db-browser.c:217
#: tools/gda-run.c:33
msgid "file name"
msgstr "название файла"

#: tools/gda-run.c:33
msgid "FILE-NAME"
msgstr "НАЗВАНИЕ ФАЙЛА"

#: tools/gda-run.c:105
#, c-format
msgid "%s: misconfigured DSN entry"
msgstr "%s: неверная запись DSN"

#: tools/gda-run.c:120
#, c-format
msgid "%s: data source '%s' not found\n"
msgstr "%s: источник данных \"%s\" не найден\n"
